import Link from "next/link";
import Image from "next/image";
import { Arrow } from "@/components/icons";
import { ContactCta, PageIntro, SectionHeading } from "@/components/ui";
import { proofPoints, siteConfig } from "@/content/site";
import { pageMetadata } from "@/lib/metadata";

export const metadata = pageMetadata("About Rohan Neure & GrowthLabs", "Meet Rohan Neure, founder of GrowthLabs, and learn about the connected approach to SEO, paid ads, websites, content, and CRO.", "/about");

export default function AboutPage() {
  return <><PageIntro eyebrow="Founder / 03" title="Direct strategy. Connected execution."><p>{siteConfig.shortBio}</p></PageIntro>
    <section className="section"><div className="shell grid gap-10 md:grid-cols-[1fr_3fr]"><p className="eyebrow">Why GrowthLabs</p><div className="grid items-start gap-10 lg:grid-cols-[1.4fr_1fr]"><div className="prose-copy space-y-6">{siteConfig.about.map((paragraph) => <p key={paragraph}>{paragraph}</p>)}<p>The focus is not digital activity for its own sake. It is to understand what customers search for, which pages and campaigns matter, where trust breaks down, and how each part of marketing can create useful business movement.</p></div><figure><Image className="aspect-square w-full object-cover" src={siteConfig.profileImage} alt="Rohan Neure, founder of GrowthLabs" width={1254} height={1254} sizes="(max-width: 1024px) 100vw, 30vw" priority /><figcaption className="mt-3 text-xs text-[var(--muted)]">Rohan Neure · Founder, GrowthLabs</figcaption></figure></div></div></section>
    <section className="section"><div className="shell"><SectionHeading eyebrow="Experience" title="Built on websites, search, campaigns, and local growth." /><div className="mt-14 grid gap-8 md:ml-[25%] md:grid-cols-2">{proofPoints.map((item) => <article className="card" key={item.metric}><p className="font-serif text-5xl tracking-[-.05em] text-[var(--accent)]">{item.metric}</p><h3 className="mt-2 font-bold">{item.label}</h3><p className="mt-4 leading-7 text-[var(--muted)]">{item.detail}</p></article>)}</div></div></section>
    <section className="section"><div className="shell"><SectionHeading eyebrow="Career" title="From SEO execution to full-funnel growth." /><ol className="mt-14 md:ml-[25%]">{siteConfig.experience.map((item) => <li className="grid gap-3 border-t border-[var(--line)] py-7 sm:grid-cols-[11rem_1fr]" key={item.title}><p className="eyebrow">{item.period}</p><div><h3 className="font-serif text-2xl">{item.title}</h3><p className="mt-1 font-semibold text-[var(--accent)]">{item.organization}</p><p className="mt-3 max-w-2xl leading-7 text-[var(--muted)]">{item.detail}</p></div></li>)}</ol><div className="mt-12 grid gap-8 md:ml-[25%] md:grid-cols-2">{siteConfig.education.map((item) => <article className="card" key={item.title}><p className="eyebrow">{item.period}</p><h3 className="mt-4 font-serif text-2xl">{item.title}</h3><p className="mt-2 text-[var(--muted)]">{item.organization}</p></article>)}</div></div></section>
    <section className="section"><div className="shell"><SectionHeading eyebrow="Working principles" title="How the work gets done matters." /><div className="mt-14 grid gap-8 md:ml-[25%] md:grid-cols-2">{siteConfig.values.map((value) => <article className="card" key={value.title}><h3 className="font-serif text-2xl">{value.title}</h3><p className="mt-3 leading-7 text-[var(--muted)]">{value.detail}</p></article>)}</div><div className="mt-12 md:ml-[25%]"><Link className="text-link" href={siteConfig.socials[0].href} target="_blank" rel="me noopener noreferrer">Connect with Rohan on LinkedIn <Arrow direction="up-right" /></Link></div></div></section><ContactCta /></>;
}
