import Image from "next/image";
import Link from "next/link";
import { Arrow } from "@/components/icons";
import { PageStructuredData } from "@/components/structured-data";
import { PageIntro, SectionHeading } from "@/components/ui";
import { services, siteConfig } from "@/content/site";
import { pageMetadata } from "@/lib/metadata";
import { agencyAssets } from "@/content/agency-assets";

export const metadata = pageMetadata("About Rohan Neure | SEO, Google Ads & Meta Ads", "Meet Rohan Neure, founder of GrowthLabs and a growth marketer working across SEO, Google Ads, Meta Ads, landing pages, analytics and CRO.", "/about");

const principles = [
  ["Search intent first", "Understand what potential customers search for and need before deciding which pages, campaigns or content should be created."],
  ["SEO and CRO together", "Rankings create opportunity. Clear messaging, trust and conversion paths turn that opportunity into business."],
  ["Connected execution", "SEO, paid ads, social content, websites, landing pages and tracking should support one coherent journey."],
  ["Practical growth", "Marketing activity should connect to qualified traffic, enquiries, bookings and sales where measurement permits."],
  ["Clarity before execution", "Understand the business problem before selecting channels, services or packages."],
];
const process = [
  ["Understand the business", "Clarify the offer, audience, economics, goals, current marketing and definition of a qualified result."],
  ["Review the evidence", "Examine search demand, competitors, website, campaigns, local visibility, analytics, tracking and lead handling."],
  ["Identify the constraint", "Decide what most limits growth now: demand, message, page, campaign, trust, tracking or follow-up."],
  ["Build the right intervention", "Implement or guide the agreed SEO, advertising, social, website, content, local-search or CRO work."],
  ["Learn and improve", "Use performance and business feedback to decide the next investment."],
];
const faqs = [
  ["What is GrowthLabs by Rohan Neure?", "GrowthLabs is a founder-led digital marketing agency and consultancy in Nepal connecting SEO, advertising, social media, websites, content, local search, analytics and CRO around measurable business growth."],
  ["Who founded GrowthLabs?", "Rohan Neure founded GrowthLabs and remains directly involved in strategy, priorities and review."],
  ["Where is GrowthLabs based?", "GrowthLabs is based at Sallaghari Shopping Complex, Bhaktapur 44800, Nepal, and serves Kathmandu Valley and businesses across Nepal."],
  ["Will I work directly with Rohan?", "Yes. Rohan remains directly involved in understanding the business, setting priorities and reviewing the work."],
  ["Does GrowthLabs work remotely?", "Yes. Online appointments are available, with on-site services where appropriate and agreed."],
  ["What size of business is the best fit?", "GrowthLabs suits businesses with a real offer, an owner or team able to provide input, a desire to improve measurable growth and willingness to fix the website or customer journey—not only increase activity."],
  ["Does GrowthLabs offer every service as a package?", "No. Engagements follow the problem and may begin with an audit, strategy, focused project or ongoing programme."],
  ["How do we start?", "Share the website, primary offer, target market, current marketing and biggest challenge through the contact page, email, phone or WhatsApp."],
];

export default function AboutPage() {
  return <>
    <PageIntro breadcrumbs={[{ label: "About" }]} eyebrow="Founder · Growth marketer · SEO, Google Ads & Meta Ads specialist" title="Direct strategy. Hands-on search, paid media and conversion work." visual={agencyAssets.analytics}><p>GrowthLabs by Rohan Neure is a founder-led digital marketing agency and consultancy helping businesses improve visibility, attract better traffic and turn more of that traffic into qualified enquiries, bookings and sales.</p><p className="mt-4">Rohan connects SEO, Google Ads, Meta Ads, social media, content, websites, landing pages, local search, analytics, tracking and conversion rate optimisation around one customer journey and one clear business objective.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link className="button button-primary" href={siteConfig.cta.primary.href} data-cta-intent="growth-review" data-cta-location="about-hero" data-cta-channel="contact">{siteConfig.cta.primary.headerLabel} <Arrow /></Link><Link className="button" href="/advertising-agency-in-nepal">Explore Google & Meta Ads <Arrow /></Link></div></PageIntro>
    <div className="border-y border-[var(--line)]"><ul className="shell grid py-1 text-sm font-semibold sm:grid-cols-2 lg:grid-cols-4">{["Direct founder involvement", "Based in Bhaktapur", "Serving Kathmandu Valley and Nepal", "Online and on-site support"].map((item) => <li className="py-4" key={item}>{item}</li>)}</ul></div>
    <section className="section"><div className="shell"><SectionHeading eyebrow="Marketing built to rank, convert and grow" title="Businesses experience one customer journey—not separate channels." copy="A person may discover a business through search, see an advertisement, check social proof, compare the website, return through a branded query and finally call or enquire. GrowthLabs was built to connect those moments." /><p className="prose-copy mt-10 md:ml-[25%]">The work begins with the audience, offer, demand, competition, website and conversion path. Channels are selected after the problem is understood. Reporting decides what should improve next—not simply whether activity happened.</p></div></section>
    <section className="section section-dark"><div className="shell grid items-center gap-12 lg:grid-cols-[.8fr_1.2fr]"><figure className="border border-white/30 bg-[var(--sun)] p-3"><Image className="aspect-square w-full object-cover grayscale" src={siteConfig.profileImage} alt="Rohan Neure, founder of GrowthLabs in Nepal" width={1254} height={1254} sizes="(max-width:1024px) 100vw, 40vw" priority /><figcaption className="mt-3 font-mono text-[.68rem] uppercase tracking-[.04em] text-[var(--ink)]">Rohan Neure · Founder, GrowthLabs</figcaption></figure><div><p className="eyebrow !text-[var(--sun)]">Founder · Growth marketer · SEO, Google Ads & Meta Ads specialist</p><h2 className="section-title mt-6">The person who understands the problem stays close to the work.</h2><p className="mt-6 text-lg leading-8 text-white/70">Rohan Neure is the founder of GrowthLabs and a performance and growth marketer with more than four years of experience across SEO, Google Ads, Meta Ads, TikTok Ads, CRO, analytics, tracking, automation, website strategy and landing-page optimisation.</p><p className="mt-5 leading-7 text-white/60">Direct access reduces the distance between discovery, strategy, implementation and review. When evidence changes the priority, the reasoning stays visible.</p><div className="mt-8 flex flex-wrap gap-3"><Link className="button border-white text-white hover:bg-[var(--sun)] hover:text-[var(--ink)]" href="/seo-expert-in-nepal">Explore SEO expertise <Arrow /></Link><Link className="button border-white text-white hover:bg-[var(--sun)] hover:text-[var(--ink)]" href="/advertising-agency-in-nepal">Explore Google & Meta Ads <Arrow /></Link></div></div></div></section>
    <section className="section"><div className="shell"><SectionHeading eyebrow="Experience and education" title="Built through hands-on search and growth work." /><ol className="mt-14 md:ml-[25%]">{[...siteConfig.experience, ...siteConfig.education].map((item) => <li className="grid gap-3 border-t border-[var(--line)] py-6 sm:grid-cols-[11rem_1fr]" key={`${item.period}-${item.title}`}><p className="eyebrow">{item.period}</p><div><h3 className="font-serif text-2xl">{item.title}</h3><p className="mt-1 font-semibold text-[var(--accent)]">{item.organization}</p>{"detail" in item && item.detail && <p className="mt-3 leading-7 text-[var(--muted)]">{item.detail}</p>}</div></li>)}</ol></div></section>
    <section className="section"><div className="shell"><SectionHeading eyebrow="The GrowthLabs story" title="From search execution to a connected growth system." copy="GrowthLabs began with the belief that better marketing decisions start with understanding what customers are trying to find and what they need to trust before acting. As the work expanded, one pattern remained: channels work better when they share the same audience insight, offer, landing experience and measurement." /><p className="prose-copy mt-10 md:ml-[25%]">Today, GrowthLabs operates as a founder-led agency and consultancy at Sallaghari Shopping Complex in Bhaktapur, serving Kathmandu Valley and businesses across Nepal. Engagements can begin with a focused audit or strategy and expand into connected implementation where appropriate.</p></div></section>
    <section className="section section-dark"><div className="shell"><SectionHeading eyebrow="One system, connected capability groups" title="Build the combination the business actually needs." copy="The service list is not a compulsory package. Scope follows the business constraint, customer journey, available resources and measurable objective." /><div className="mt-16">{services.map((service, index) => <article className="grid gap-5 border-t border-white/25 py-7 md:grid-cols-[5rem_.8fr_1.2fr]" key={service.slug}><p className="font-mono text-xs text-[var(--sun)]">0{index + 1}</p><h3 className="font-serif text-3xl leading-none tracking-[-.045em]">{service.title}</h3><p className="leading-7 text-white/65">{service.summary}</p></article>)}</div><Link className="button mt-12 border-white text-white hover:bg-[var(--sun)] hover:text-[var(--ink)]" href="/services">Explore all digital marketing services <Arrow /></Link></div></section>
    <section className="section"><div className="shell"><SectionHeading eyebrow="Business-model relevance" title="Work shaped around how your customers search and decide." copy="GrowthLabs supports service businesses, hotels, travel and trekking agencies, ecommerce brands, restaurants, startups, consultants, local organisations, professional-service providers and agencies requiring specialist support." /><div className="mt-10 flex flex-wrap gap-5 md:ml-[25%]"><Link className="text-link" href="/hotel-digital-marketing-agency">Hotel marketing <Arrow /></Link><Link className="text-link" href="/seo-for-travel-agency">Travel SEO <Arrow /></Link><Link className="text-link" href="/digital-marketing-agency-in-nepal">Agency services in Nepal <Arrow /></Link></div></div></section>
    <section className="section"><div className="shell"><SectionHeading eyebrow="How the work gets done matters" title="Five principles behind every engagement." /><div className="mt-14 grid gap-8 md:ml-[25%] md:grid-cols-2">{principles.map(([title, copy]) => <article className="card" key={title}><h3 className="font-serif text-2xl">{title}</h3><p className="mt-3 leading-7 text-[var(--muted)]">{copy}</p></article>)}</div></div></section>
    <section className="section signal-grid"><div className="shell"><SectionHeading eyebrow="A visible decision process" title="Diagnose, prioritise, build and improve." /><ol className="mt-14 border-b border-[var(--ink)] md:ml-[25%]">{process.map(([title, copy], index) => <li className="grid gap-3 border-t border-[var(--ink)] py-6 sm:grid-cols-[4rem_1fr_2fr]" key={title}><span className="font-mono text-xs">0{index + 1}</span><h3 className="font-serif text-2xl leading-none tracking-[-.04em]">{title}</h3><p className="leading-7 text-black/65">{copy}</p></li>)}</ol></div></section>
    <section className="section"><div className="shell"><SectionHeading eyebrow="Evidence needs context" title="Trust should be inspectable." copy="The anonymised Search Console and Google Ads captures on the website are source-interface evidence, not complete case studies or sole-attribution claims. GrowthLabs publishes contextual performance claims only when the platform, period, metric definition and business context can be supported. Client names and testimonials require permission." /></div></section>
    <section className="section"><div className="shell"><SectionHeading eyebrow="Bhaktapur · Kathmandu Valley · Across Nepal" title="Work with GrowthLabs online or arrange appropriate on-site support." /><address className="mt-10 grid gap-3 not-italic md:ml-[25%]"><strong className="font-serif text-2xl">{siteConfig.brandName}</strong><span>{siteConfig.location}</span><a className="text-link w-fit" href={siteConfig.cta.phone.href}>{siteConfig.cta.phone.label}: {siteConfig.phoneDisplay}</a><a className="text-link w-fit" href={siteConfig.cta.email.href}>{siteConfig.cta.email.label}</a><a className="text-link w-fit" href={siteConfig.cta.whatsapp.href} target="_blank" rel="noopener noreferrer">{siteConfig.cta.whatsapp.label} <Arrow direction="up-right" /></a><a className="text-link w-fit" href={siteConfig.mapUrl} target="_blank" rel="noopener noreferrer">View Google Business Profile <Arrow direction="up-right" /></a><a className="text-link w-fit" href={siteConfig.socials[0].href} target="_blank" rel="me noopener noreferrer">LinkedIn <Arrow direction="up-right" /></a></address></div></section>
    <section className="section"><div className="shell"><SectionHeading eyebrow="About GrowthLabs" title="Useful context before we work together." /><div className="mt-14 md:ml-[25%]">{faqs.map(([question, answer]) => <details className="group border-t border-[var(--line)] py-5" key={question}><summary className="flex min-h-11 cursor-pointer list-none items-center justify-between gap-6 font-serif text-xl"><span>{question}</span><span aria-hidden="true" className="text-[var(--accent)] group-open:rotate-45">+</span></summary><p className="prose-copy mt-4 pr-8">{answer}</p></details>)}</div></div></section>
    <section className="section signal-grid"><div className="shell grid gap-8 md:grid-cols-[1fr_3fr]"><p className="eyebrow">Start with clarity</p><div><h2 className="section-title">Tell Rohan where growth feels stuck.</h2><p className="mt-6 max-w-2xl text-lg leading-8 text-black/65">{siteConfig.cta.microcopy}</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link className="button button-primary" href={siteConfig.cta.primary.href} data-cta-intent="growth-review" data-cta-location="about-final" data-cta-channel="contact">{siteConfig.cta.primary.headerLabel} <Arrow /></Link><a className="button" href={siteConfig.cta.whatsapp.href} target="_blank" rel="noopener noreferrer" data-cta-intent="growth-review" data-cta-location="about-final" data-cta-channel="whatsapp">{siteConfig.cta.whatsapp.label} <Arrow direction="up-right" /></a></div><p className="mt-5 font-mono text-[.72rem] uppercase leading-5 tracking-[.04em] text-black/65">{siteConfig.cta.reassurance}</p></div></div></section>
    <PageStructuredData path="/about" faqs={faqs.map(([question, answer]) => ({ question, answer }))} />
  </>;
}
