import Image from "next/image";
import Link from "next/link";
import { Arrow } from "@/components/icons";
import { SectionHeading } from "@/components/ui";
import { faqs, industries, problems, process, services, siteConfig } from "@/content/site";

const serviceLinks: Record<string, { label: string; href: string }> = {
  seo: { label: "Work directly with an SEO expert in Nepal", href: "/seo-expert-in-nepal" },
  "paid-advertising": { label: "Explore advertising support", href: "/advertising-agency-in-nepal" },
  "social-media": { label: "Explore social media marketing", href: "/social-media-marketing-agency-in-nepal" },
  websites: { label: "Explore web design in Nepal", href: "/web-design-company-in-nepal" },
};

const journey = [
  { title: "Be discovered", copy: "Search visibility, local presence, useful content, social distribution and paid campaigns introduce the business to the right audience." },
  { title: "Become relevant", copy: "Clear positioning, service-specific pages and message continuity show visitors that the offer fits the problem they are trying to solve." },
  { title: "Build trust", copy: "Useful detail, transparent process, real people, credible evidence and a considered experience reduce uncertainty." },
  { title: "Make action easy", copy: "Clear calls to action, visible contact options, mobile usability and reliable follow-up remove avoidable friction." },
  { title: "Learn and improve", copy: "Search, campaign, behaviour and conversion data reveal the next constraint and direct time and budget towards it." },
];

const founderBenefits = [
  ["One point of strategic accountability", "The person who understands the commercial problem remains involved in the plan and performance review."],
  ["Faster movement from insight to implementation", "Search, campaign, content, website and CRO decisions can be made with the same context."],
  ["Recommendations based on the constraint", "The starting point may be a page, tracking issue, search opportunity, campaign or the offer itself—not a predetermined package."],
  ["Clearer reasoning", "You should know what is being done, why it matters, what evidence supports it and what should happen next."],
];

export default function HomePage() {
  const schemas = [
    { "@context": "https://schema.org", "@type": "WebSite", name: siteConfig.brandName, url: siteConfig.domain },
    { "@context": "https://schema.org", "@type": "Organization", name: siteConfig.brandName, url: siteConfig.domain, founder: { "@type": "Person", name: siteConfig.fullName, sameAs: siteConfig.socials.map((social) => social.href) }, address: { "@type": "PostalAddress", streetAddress: "Sallaghari Shopping Complex", addressLocality: "Bhaktapur", postalCode: "44800", addressCountry: "NP" }, telephone: siteConfig.phone, email: siteConfig.email },
  ];
  return <>
    <section className="shell grid gap-12 py-12 md:py-20 lg:grid-cols-[1.35fr_.65fr] lg:items-center">
      <div><p className="eyebrow">Founder-led digital growth · Bhaktapur, Kathmandu Valley and across Nepal</p><h1 className="display mt-7 !max-w-[11ch]">Digital marketing built to rank, convert and grow.</h1><p className="lede mt-8 border-t border-[var(--ink)] pt-5">GrowthLabs by Rohan Neure connects SEO, paid advertising, content, websites, tracking and conversion rate optimisation around one goal: turning the right attention into qualified enquiries, bookings and sales.</p><p className="mt-5 max-w-2xl leading-7 text-[var(--muted)]">Work directly with a growth marketer who looks beyond isolated rankings, clicks and posts to improve the complete customer journey—from discovery to decision.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link className="button button-primary" href="/contact">Get a growth review <Arrow /></Link><Link className="button" href="/services">Explore services <Arrow /></Link></div><p className="mt-4 max-w-xl text-sm leading-6 text-[var(--muted)]">Share your website and biggest growth challenge. The first conversation is practical, focused and free from a generic sales pitch.</p></div>
      <figure className="hero-portrait mx-auto w-full max-w-md"><Image className="h-auto w-full" src={siteConfig.profileImage} alt="Rohan Neure, founder of GrowthLabs in Nepal" width={1089} height={1089} sizes="(max-width: 1024px) 90vw, 36vw" priority /></figure>
    </section>
    <div className="border-y border-[var(--line)]"><ul className="shell grid divide-y divide-[var(--line)] py-1 text-sm font-semibold sm:grid-cols-2 sm:divide-y-0 lg:grid-cols-4">{["Direct founder involvement", "Strategy before channels", "SEO + ads + websites + CRO", "Online and on-site support"].map((item) => <li className="py-4 sm:px-4 sm:first:pl-0" key={item}>{item}</li>)}</ul></div>

    <section className="section"><div className="shell"><SectionHeading eyebrow="One connected growth system" title="Stop losing customers between the click and the conversion." copy="Most businesses do not lack marketing activity. The problem is that each activity is planned and measured separately while the customer experiences one continuous journey. GrowthLabs finds the gaps and connects the work that matters." /><div className="mt-14 grid gap-8 md:ml-[25%] sm:grid-cols-2">{[["Get found by people with a relevant need", "Build organic and paid visibility around real demand, not vanity traffic."], ["Give every click a convincing next step", "Connect the promise in search, content or advertising to a page that explains, reassures and converts."], ["Improve the traffic you already have", "Remove friction from messages, offers, pages, calls to action and enquiry paths."], ["Know what is creating movement", "Use tracking and reporting to identify what deserves more investment—and what does not."]].map(([title, copy]) => <article className="card" key={title}><h3 className="font-serif text-2xl">{title}</h3><p className="mt-3 leading-7 text-[var(--muted)]">{copy}</p></article>)}</div></div></section>

    <section className="section"><div className="shell"><SectionHeading eyebrow="Common growth constraints" title="Why digital marketing activity fails to become business." /><div className="mt-16 grid gap-x-8 gap-y-12 md:grid-cols-2">{problems.map((item, index) => <article className="card" key={item.title}><p className="eyebrow">0{index + 1}</p><h3 className="mt-5 font-serif text-3xl">{item.title}</h3><p className="mt-4 max-w-xl leading-7 text-[var(--muted)]">{item.copy}</p></article>)}</div></div></section>

    <section className="section bg-[linear-gradient(135deg,#21170d,#4a2005)] text-[var(--paper)]"><div className="shell"><SectionHeading eyebrow="Capabilities around the journey" title="Use the right channel at the right stage—not every channel at once." copy="The best plan depends on the offer, audience, market, website, evidence and current bottleneck. GrowthLabs selects and connects the capabilities that can create the clearest next improvement." /><div className="mt-16 grid gap-10 md:grid-cols-2">{services.map((service, index) => { const link = serviceLinks[service.slug]; return <article className="border-t border-white/30 pt-5" key={service.slug}><p className="eyebrow !text-[var(--sun)]">0{index + 1}</p><h3 className="mt-5 font-serif text-3xl">{service.title}</h3><p className="mt-4 leading-7 text-white/65">{service.summary}</p>{link && <Link className="mt-5 inline-flex items-center gap-2 border-b border-white/40 pb-1 text-sm font-semibold text-white" href={link.href}>{link.label} <Arrow /></Link>}</article>})}</div><Link className="button mt-12 border-white text-white hover:bg-white hover:text-[var(--ink)]" href="/services">Explore every service <Arrow /></Link></div></section>

    <section className="section"><div className="shell"><SectionHeading eyebrow="How the system works" title="Give every stage a purpose." /><ol className="mt-14 md:ml-[25%]">{journey.map((step, index) => <li className="grid gap-3 border-t border-[var(--line)] py-6 sm:grid-cols-[4rem_1fr_2fr]" key={step.title}><span className="eyebrow">0{index + 1}</span><h3 className="font-serif text-2xl">{step.title}</h3><p className="leading-7 text-[var(--muted)]">{step.copy}</p></li>)}</ol></div></section>

    <section className="section bg-[var(--ink)] text-[var(--paper)]"><div className="shell grid items-center gap-12 lg:grid-cols-[.8fr_1.2fr]"><figure><Image className="aspect-square w-full object-cover" src={siteConfig.profileImage} alt="Rohan Neure, founder of GrowthLabs" width={1089} height={1089} sizes="(max-width: 1024px) 100vw, 40vw" /></figure><div><p className="eyebrow !text-[var(--sun)]">GrowthLabs by Rohan Neure</p><h2 className="section-title mt-6">Strategy stays close to the work.</h2><p className="mt-6 max-w-2xl text-lg leading-8 text-white/70">You work directly with Rohan to understand the audience, offer, competitors, search demand, current marketing and business goal. That context shapes the priorities and execution.</p><div className="mt-9 grid gap-6 sm:grid-cols-2">{founderBenefits.map(([title, copy]) => <article className="border-t border-white/25 pt-4" key={title}><h3 className="font-serif text-xl">{title}</h3><p className="mt-2 text-sm leading-6 text-white/60">{copy}</p></article>)}</div><Link className="button mt-9 border-white text-white hover:bg-white hover:text-[var(--ink)]" href="/about">About GrowthLabs and Rohan <Arrow /></Link></div></div></section>

    <section className="section"><div className="shell"><SectionHeading eyebrow="Evidence before promises" title="Measure movement that matters to the business." copy="The scorecard may connect search visibility, qualified visits, campaign efficiency, landing-page behaviour, calls, WhatsApp actions, enquiries, bookings or sales with the pages and channels that influenced them. GrowthLabs does not promise a guaranteed ranking, lead volume or return." /><div className="mt-14 grid gap-8 md:ml-[25%] md:grid-cols-3">{[["Baselines before conclusions", "Understand the starting position before crediting a change."], ["Context with every result", "Record the period, scope, market conditions and intervention behind meaningful movement."], ["Decisions, not dashboard decoration", "Reporting should end with what to continue, change, stop or test."]].map(([title, copy]) => <article className="card" key={title}><h3 className="font-serif text-2xl">{title}</h3><p className="mt-3 leading-7 text-[var(--muted)]">{copy}</p></article>)}</div></div></section>

    <section className="section"><div className="shell"><SectionHeading eyebrow="Who GrowthLabs helps" title="Built for businesses with something real to grow." /><div className="mt-14 grid gap-8 sm:grid-cols-2 lg:grid-cols-3">{industries.map((industry) => <article className="card" key={industry.title}><h3 className="font-serif text-2xl">{industry.title}</h3><p className="mt-3 text-sm leading-6 text-[var(--muted)]">{industry.copy}</p>{industry.title.startsWith("Hotels") && <Link className="text-link mt-5" href="/hotel-digital-marketing-agency">Hotel digital marketing <Arrow /></Link>}{industry.title.startsWith("Travel") && <Link className="text-link mt-5" href="/seo-for-travel-agency">SEO for travel agencies <Arrow /></Link>}</article>)}</div></div></section>

    <section className="section"><div className="shell"><SectionHeading eyebrow="Clarity before execution" title="Know what should be built next—and why." /><ol className="mt-14 md:ml-[25%]">{process.map((step, index) => <li className="grid gap-3 border-t border-[var(--line)] py-6 sm:grid-cols-[4rem_1fr_2fr]" key={step.title}><span className="eyebrow">0{index + 1}</span><h3 className="font-serif text-2xl">{step.title}</h3><p className="leading-7 text-[var(--muted)]">{step.copy}</p></li>)}</ol><div className="mt-10 md:ml-[25%]"><Link className="button button-primary" href="/contact">Get a growth review <Arrow /></Link></div></div></section>

    <section className="section"><div className="shell"><SectionHeading eyebrow="A useful working relationship" title="Fit matters on both sides." /><div className="mt-14 grid gap-10 md:ml-[25%] md:grid-cols-2"><article><h3 className="font-serif text-3xl">GrowthLabs may be a good fit if…</h3><ul className="mt-5">{["You want senior, direct involvement rather than a hand-off after the sales call.", "You want SEO, advertising, content and the website to support one commercial journey.", "You are willing to improve weak pages and measurement—not only increase activity.", "You value transparent reasoning, realistic expectations and steady improvement."].map((item) => <li className="border-t border-[var(--line)] py-3" key={item}>{item}</li>)}</ul></article><article><h3 className="font-serif text-3xl">It may not be the right fit if…</h3><ul className="mt-5">{["You want guaranteed rankings, instant results or a fixed return regardless of the starting point.", "You only want the cheapest volume of posts, links, traffic or clicks.", "You cannot provide the access, context, approvals or implementation support the work requires."].map((item) => <li className="border-t border-[var(--line)] py-3" key={item}>{item}</li>)}</ul></article></div></div></section>

    <section className="section"><div className="shell"><SectionHeading eyebrow="Before the first conversation" title="Frequently asked questions." /><div className="mt-14 md:ml-[25%]">{faqs.map((item, index) => <details className="group border-t border-[var(--line)] py-5" key={item.question} open={index === 0}><summary className="flex min-h-11 cursor-pointer list-none items-center justify-between gap-6 font-serif text-xl"><span>{item.question}</span><span aria-hidden="true" className="text-[var(--accent)] group-open:rotate-45">+</span></summary><p className="prose-copy mt-4 pr-8">{item.answer}</p></details>)}</div></div></section>
    <section className="section bg-[var(--accent)] text-white"><div className="shell grid gap-8 md:grid-cols-[1fr_3fr]"><p className="eyebrow !text-white/65">Start with the real constraint</p><div><h2 className="section-title">Find what is limiting growth. Build the right next step.</h2><p className="mt-6 max-w-2xl text-lg leading-8 text-white/75">Tell GrowthLabs what you sell, who you want to reach and where the current journey is underperforming.</p><div className="mt-8 flex flex-col gap-4 sm:flex-row"><Link className="button border-white text-white hover:bg-white hover:text-[var(--accent)]" href="/contact">Get a growth review <Arrow /></Link><a className="button border-white/50 text-white hover:bg-white hover:text-[var(--accent)]" href={siteConfig.whatsapp} target="_blank" rel="noopener noreferrer">WhatsApp Rohan <Arrow direction="up-right" /></a></div><p className="mt-5 text-sm text-white/70">Prefer email? {siteConfig.email} · Prefer to call? {siteConfig.phoneDisplay}</p></div></div></section>
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schemas).replace(/</g, "\\u003c") }} />
  </>;
}
