import Image from "next/image";
import Link from "next/link";
import { Arrow } from "@/components/icons";
import { PerformanceEvidence } from "@/components/search-evidence";
import { CredentialProof } from "@/components/credential-proof";
import { SectionHeading } from "@/components/ui";
import { PageStructuredData } from "@/components/structured-data";
import { faqs, industries, problems, process, services, siteConfig } from "@/content/site";
import { insights } from "@/content/insights";

const serviceLinks: Record<string, { label: string; href: string }> = {
  seo: { label: "Work directly with an SEO expert in Nepal", href: "/seo-expert-in-nepal" },
  "paid-advertising": { label: "Explore advertising support", href: "/advertising-agency-in-nepal" },
  "social-media": { label: "Explore social media marketing", href: "/social-media-marketing-agency-in-nepal" },
  websites: { label: "Explore web design in Nepal", href: "/web-design-company-in-nepal" },
  "local-seo": { label: "Explore local SEO services", href: "/local-seo-services-in-nepal" },
};

const insightPreview = ["what-is-seo", "social-media-content-calendar", "google-business-profile-optimization"]
  .map((slug) => insights.find((article) => article.slug === slug))
  .filter((article): article is NonNullable<typeof article> => Boolean(article));

const journey = [
  { title: "Be discovered", copy: "Search visibility, local presence, useful content, social distribution and paid campaigns introduce the business to the right audience." },
  { title: "Become relevant", copy: "Clear positioning, service-specific pages and message continuity show visitors that the offer fits the problem they are trying to solve." },
  { title: "Build trust", copy: "Useful detail, transparent process, real people, credible evidence and a considered experience reduce uncertainty." },
  { title: "Make action easy", copy: "Clear calls to action, visible contact options, mobile usability and reliable follow-up remove avoidable friction." },
  { title: "Learn and improve", copy: "Search, campaign, behaviour and conversion data reveal the next constraint and direct time and budget towards it." },
];

const founderBenefits = [
  ["One point of strategic accountability", "The person who understands the commercial problem remains involved in the plan and performance review."],
  ["Faster movement from insight to implementation", "Search, campaign, content, website and CRO decisions can be made with the same context."],
  ["Recommendations based on the constraint", "The starting point may be a page, tracking issue, search opportunity, campaign or the offer itself—not a predetermined package."],
  ["Clearer reasoning", "You should know what is being done, why it matters, what evidence supports it and what should happen next."],
];

export default function HomePage() {
  return <>
    <section className="relative overflow-hidden border-b border-[var(--ink)] bg-[var(--surface)]"><div aria-hidden="true" className="signal-grid absolute inset-y-0 right-0 hidden w-[29%] lg:block" /><div className="shell relative grid gap-14 py-12 md:py-20 lg:grid-cols-[1.35fr_.65fr] lg:items-end"><div><p className="eyebrow">Founder-led SEO, Google Ads & Meta Ads / Bhaktapur → Nepal</p><h1 className="display mt-8 !max-w-[12ch]">SEO, Google Ads & <span className="bg-[var(--sun)] px-[.06em]">Meta Ads</span> built to convert and grow.</h1><div className="growth-trace mt-6 max-w-3xl" /><div className="mt-7 flex flex-col gap-3 sm:flex-row"><Link className="button button-primary" href={siteConfig.cta.primary.href} data-cta-intent="growth-review" data-cta-location="home-hero" data-cta-channel="contact">{siteConfig.cta.primary.label} <Arrow /></Link><a className="button" href="#performance-evidence" data-cta-intent="proof" data-cta-location="home-hero">Inspect performance proof <Arrow /></a></div><p className="lede mt-7 border-t border-[var(--ink)] pt-5">GrowthLabs by Rohan Neure connects SEO, Google Ads, Meta Ads, landing pages, tracking and conversion rate optimisation around one goal: turning the right attention into qualified enquiries, bookings and sales.</p><p className="mt-5 max-w-2xl leading-7 text-[var(--muted)]">Work directly with a growth marketer who looks beyond isolated rankings, clicks and posts to improve the complete customer journey—from discovery to decision.</p><p className="mt-4 max-w-xl font-mono text-[.68rem] uppercase leading-5 tracking-[.04em] text-[var(--muted)]">{siteConfig.cta.reassurance} Bring your URL, offer, target market and current channel data.</p></div><figure className="hero-portrait mx-auto w-full max-w-md"><Image className="aspect-[4/5] h-auto w-full object-cover object-top" src={siteConfig.profileImage} alt="Rohan Neure, founder of GrowthLabs in Nepal" width={1254} height={1254} sizes="(max-width: 1024px) 90vw, 36vw" priority /></figure></div></section>
    <div className="signal-band"><ul className="shell grid py-1 font-mono text-[.68rem] font-bold uppercase tracking-[.055em] sm:grid-cols-2 lg:grid-cols-4">{["4+ years across growth", "SEO demand capture", "Google Ads acquisition", "Meta Ads + CRO"].map((item, index) => <li className="flex items-center gap-3 border-black/25 py-4 sm:border-r sm:px-4 sm:first:pl-0 sm:last:border-0" key={item}><span>0{index + 1}</span>{item}</li>)}</ul></div>

    <section className="section"><div className="shell"><SectionHeading eyebrow="One connected growth system" title="Stop losing customers between the click and the conversion." copy="Most businesses do not lack marketing activity. The problem is that each activity is planned and measured separately while the customer experiences one continuous journey. GrowthLabs finds the gaps and connects the work that matters." /><div className="mt-14 grid gap-8 md:ml-[25%] sm:grid-cols-2">{[["Get found by people with a relevant need", "Build organic and paid visibility around real demand, not vanity traffic."], ["Give every click a convincing next step", "Connect the promise in search, content or advertising to a page that explains, reassures and converts."], ["Improve the traffic you already have", "Remove friction from messages, offers, pages, calls to action and enquiry paths."], ["Know what is creating movement", "Use tracking and reporting to identify what deserves more investment—and what does not."]].map(([title, copy]) => <article className="card" key={title}><h3 className="font-serif text-2xl">{title}</h3><p className="mt-3 leading-7 text-[var(--muted)]">{copy}</p></article>)}</div></div></section>

    <PerformanceEvidence sectionId="performance-evidence" dark searchIds={["australian-agency"]} paidIds={["london-home-services-ads", "saas-google-ads"]} title="Organic search and Google Ads evidence—with the numbers made visible." copy="Three source captures show monitored organic visibility and account-reported paid-campaign activity across agency, home-services and SaaS markets. The figures remain tied to their platform, account and period: inspectable evidence for a qualified conversation, not guaranteed outcomes or complete case studies." />
    <CredentialProof ids={["googleAds", "metaAds", "semrush", "hubspot", "amazonAds", "googleReviews"]} title="Certified across the platforms behind modern acquisition and growth." copy="GrowthLabs brings supplied Google Ads, Meta Ads, Amazon Ads, Semrush and HubSpot partner credentials together with Google Reviews artwork displaying a 5.0 rating. Founder Rohan Neure has confirmed the business is authorised to present these assets." />

    <section className="section"><div className="shell"><SectionHeading eyebrow="Common growth constraints" title="Why digital marketing activity fails to become business." /><div className="mt-16 grid gap-x-8 gap-y-12 md:grid-cols-2">{problems.map((item, index) => <article className="card" key={item.title}><p className="eyebrow">0{index + 1}</p><h3 className="mt-5 font-serif text-3xl">{item.title}</h3><p className="mt-4 max-w-xl leading-7 text-[var(--muted)]">{item.copy}</p></article>)}</div></div></section>

    <section className="section section-dark"><div className="shell"><SectionHeading eyebrow="Capabilities around the journey" title="Use the right channel at the right stage—not every channel at once." copy="The best plan depends on the offer, audience, market, website, evidence and current bottleneck. GrowthLabs selects and connects the capabilities that can create the clearest next improvement." /><div className="mt-16 border-b border-white/20">{services.map((service, index) => { const link = serviceLinks[service.slug]; return <article className="grid gap-5 border-t border-white/25 py-7 md:grid-cols-[5rem_.8fr_1.2fr_auto] md:items-start" key={service.slug}><p className="font-mono text-xs text-[var(--sun)]">0{index + 1}</p><h3 className="font-serif text-3xl leading-none tracking-[-.045em]">{service.title}</h3><p className="leading-7 text-white/65">{service.summary}</p>{link && <Link className="w-fit border-b border-white/40 pb-1 text-sm font-semibold text-white hover:text-[var(--sun)]" href={link.href}>{link.label} <Arrow /></Link>}</article>})}</div><div className="mt-12 flex flex-wrap gap-5"><Link className="button border-white text-white hover:bg-[var(--sun)] hover:text-[var(--ink)]" href="/services">Explore every service <Arrow /></Link><Link className="text-link !text-[var(--sun)]" href="/digital-marketing-agency-in-nepal">See the complete Nepal agency model <Arrow /></Link></div></div></section>

    <section className="section"><div className="shell"><SectionHeading eyebrow="How the system works" title="Give every stage a purpose." /><ol className="mt-14 md:ml-[25%]">{journey.map((step, index) => <li className="grid gap-3 border-t border-[var(--line)] py-6 sm:grid-cols-[4rem_1fr_2fr]" key={step.title}><span className="eyebrow">0{index + 1}</span><h3 className="font-serif text-2xl">{step.title}</h3><p className="leading-7 text-[var(--muted)]">{step.copy}</p></li>)}</ol></div></section>

    <section className="section section-dark"><div className="shell grid items-center gap-12 lg:grid-cols-[.8fr_1.2fr]"><figure className="border border-white/30 bg-[var(--sun)] p-3"><Image className="aspect-[4/5] w-full object-cover object-top grayscale" src={siteConfig.profileImage} alt="Rohan Neure, founder of GrowthLabs" width={1254} height={1254} sizes="(max-width: 1024px) 100vw, 40vw" /></figure><div><p className="eyebrow !text-[var(--sun)]">GrowthLabs by Rohan Neure</p><h2 className="section-title mt-6">Strategy stays close to the work.</h2><p className="mt-6 max-w-2xl text-lg leading-8 text-white/70">You work directly with Rohan to understand the audience, offer, competitors, search demand, current marketing and business goal. That context shapes the priorities and execution.</p><blockquote className="mt-8 border-l-2 border-[var(--sun)] pl-5 font-serif text-2xl leading-tight tracking-[-.035em] text-white/90">“You should know what is being done, why it matters and what the evidence says to do next.”</blockquote><div className="mt-9 grid gap-6 sm:grid-cols-2">{founderBenefits.map(([title, copy]) => <article className="border-t border-white/25 pt-4" key={title}><h3 className="font-serif text-xl">{title}</h3><p className="mt-2 text-sm leading-6 text-white/60">{copy}</p></article>)}</div><Link className="button mt-9 border-white text-white hover:bg-[var(--sun)] hover:text-[var(--ink)]" href="/about">About GrowthLabs and Rohan <Arrow /></Link></div></div></section>

    <section className="section"><div className="shell"><SectionHeading eyebrow="Evidence before promises" title="Measure movement that matters to the business." copy="The scorecard may connect search visibility, qualified visits, campaign efficiency, landing-page behaviour, calls, WhatsApp actions, enquiries, bookings or sales with the pages and channels that influenced them. GrowthLabs does not promise a guaranteed ranking, lead volume or return." /><div className="mt-14 grid gap-8 md:ml-[25%] md:grid-cols-3">{[["Baselines before conclusions", "Understand the starting position before crediting a change."], ["Context with every result", "Record the period, scope, market conditions and intervention behind meaningful movement."], ["Decisions, not dashboard decoration", "Reporting should end with what to continue, change, stop or test."]].map(([title, copy]) => <article className="card" key={title}><h3 className="font-serif text-2xl">{title}</h3><p className="mt-3 leading-7 text-[var(--muted)]">{copy}</p></article>)}</div></div></section>

    <section className="section"><div className="shell"><SectionHeading eyebrow="Who GrowthLabs helps" title="Built for businesses with something real to grow." /><div className="mt-14 grid gap-8 sm:grid-cols-2 lg:grid-cols-3">{industries.map((industry) => <article className="card" key={industry.title}><h3 className="font-serif text-2xl">{industry.title}</h3><p className="mt-3 text-sm leading-6 text-[var(--muted)]">{industry.copy}</p>{industry.title.startsWith("Hotels") && <Link className="text-link mt-5" href="/hotel-digital-marketing-agency">Hotel digital marketing <Arrow /></Link>}{industry.title.startsWith("Travel") && <Link className="text-link mt-5" href="/seo-for-travel-agency">SEO for travel agencies <Arrow /></Link>}</article>)}</div></div></section>

    <section className="section bg-[var(--surface)]"><div className="shell"><SectionHeading eyebrow="GrowthLabs insights" title="Useful answers before another marketing decision." copy="Source-backed guides turn search, platform and website questions into practical checklists, comparisons and operating tools. No empty article cards and no filler written merely to target a phrase." /><div className="mt-14 grid border-b border-[var(--line-strong)] md:ml-[25%] lg:grid-cols-3">{insightPreview.map((article, index) => <Link className="group flex min-h-80 flex-col border-t border-[var(--line-strong)] p-6 transition-colors hover:bg-[var(--sun)] lg:border-r lg:last:border-r-0" href={`/insights/${article.slug}`} key={article.slug}><p className="font-mono text-[.65rem] font-bold uppercase tracking-[.05em] text-[var(--accent)]">0{index + 1} / {article.category} / {article.readingTime}</p><h3 className="mt-9 font-serif text-3xl leading-none tracking-[-.05em]">{article.shortTitle}</h3><p className="mt-4 text-sm leading-6 text-[var(--muted)]">{article.description}</p><span className="mt-auto flex items-center gap-2 pt-8 text-sm font-bold">Read the guide <Arrow /></span></Link>)}</div><div className="mt-10 md:ml-[25%]"><Link className="button button-primary" href="/insights">Explore all insights <Arrow /></Link></div></div></section>

    <section className="section"><div className="shell"><SectionHeading eyebrow="Clarity before execution" title="Know what should be built next—and why." /><ol className="mt-14 md:ml-[25%]">{process.map((step, index) => <li className="grid gap-3 border-t border-[var(--line)] py-6 sm:grid-cols-[4rem_1fr_2fr]" key={step.title}><span className="eyebrow">0{index + 1}</span><h3 className="font-serif text-2xl">{step.title}</h3><p className="leading-7 text-[var(--muted)]">{step.copy}</p></li>)}</ol><div className="mt-10 md:ml-[25%]"><Link className="button button-primary" href={siteConfig.cta.primary.href} data-cta-intent="growth-review" data-cta-location="home-process" data-cta-channel="contact">{siteConfig.cta.primary.headerLabel} <Arrow /></Link></div></div></section>

    <section className="section"><div className="shell"><SectionHeading eyebrow="A useful working relationship" title="Fit matters on both sides." /><div className="mt-14 grid gap-10 md:ml-[25%] md:grid-cols-2"><article><h3 className="font-serif text-3xl">GrowthLabs may be a good fit if…</h3><ul className="mt-5">{["You want senior, direct involvement rather than a hand-off after the sales call.", "You want SEO, advertising, content and the website to support one commercial journey.", "You are willing to improve weak pages and measurement—not only increase activity.", "You value transparent reasoning, realistic expectations and steady improvement."].map((item) => <li className="border-t border-[var(--line)] py-3" key={item}>{item}</li>)}</ul></article><article><h3 className="font-serif text-3xl">It may not be the right fit if…</h3><ul className="mt-5">{["You want guaranteed rankings, instant results or a fixed return regardless of the starting point.", "You only want the cheapest volume of posts, links, traffic or clicks.", "You cannot provide the access, context, approvals or implementation support the work requires."].map((item) => <li className="border-t border-[var(--line)] py-3" key={item}>{item}</li>)}</ul></article></div></div></section>

    <section className="section"><div className="shell"><SectionHeading eyebrow="Before the first conversation" title="Frequently asked questions." /><div className="mt-14 md:ml-[25%]">{faqs.map((item, index) => <details className="group border-t border-[var(--line)] py-5" key={item.question} open={index === 0}><summary className="flex min-h-11 cursor-pointer list-none items-center justify-between gap-6 font-serif text-xl"><span>{item.question}</span><span aria-hidden="true" className="text-[var(--accent)] group-open:rotate-45">+</span></summary><p className="prose-copy mt-4 pr-8">{item.answer}</p></details>)}</div></div></section>
    <section className="section signal-grid"><div className="shell grid gap-8 md:grid-cols-[1fr_3fr]"><p className="eyebrow">Start with the real constraint</p><div><h2 className="section-title">Bring the growth problem. Leave with a clearer next move.</h2><p className="mt-6 max-w-2xl text-lg leading-8 text-black/65">{siteConfig.cta.microcopy}</p><div className="mt-8 flex flex-col gap-4 sm:flex-row"><Link className="button button-primary" href={siteConfig.cta.primary.href} data-cta-intent="growth-review" data-cta-location="home-final" data-cta-channel="contact">{siteConfig.cta.primary.label} <Arrow /></Link><a className="button" href={siteConfig.cta.whatsapp.href} target="_blank" rel="noopener noreferrer" data-cta-intent="growth-review" data-cta-location="home-final" data-cta-channel="whatsapp">{siteConfig.cta.whatsapp.label} <Arrow direction="up-right" /></a></div><p className="mt-5 font-mono text-[.72rem] uppercase leading-5 tracking-[.04em] text-black/65">{siteConfig.cta.reassurance}</p></div></div></section>
    <PageStructuredData path="/" faqs={faqs} />
  </>;
}
