import Link from "next/link";
import Image from "next/image";
import { Arrow } from "@/components/icons";
import { ContactCta, SectionHeading } from "@/components/ui";
import { faqs, industries, problems, process, proofPoints, services, siteConfig, tools } from "@/content/site";

export default function HomePage() {
  const faqSchema = { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: faqs.map((item) => ({ "@type": "Question", name: item.question, acceptedAnswer: { "@type": "Answer", text: item.answer } })) };
  return <>
    <section className="shell grid min-h-[calc(100svh-73px)] content-between gap-14 py-10 md:py-16">
      <p className="eyebrow">Founder-led · Kathmandu & across Nepal</p>
      <div className="grid items-end gap-10 lg:grid-cols-[2.2fr_1fr]">
        <div><p className="eyebrow mb-6">SEO · Ads · Websites · CRO</p><h1 className="display !max-w-[11ch]">Digital marketing built to rank, convert, and grow.</h1><p className="lede mt-8 border-t border-[var(--ink)] pt-5">We help Nepal businesses rank higher, attract better traffic, and convert more visitors into leads through SEO, ads, and growth-focused websites.</p></div>
        <figure className="hero-portrait mx-auto w-full max-w-sm lg:mx-0 lg:max-w-md"><Image className="h-auto w-full" src={siteConfig.profileImage} alt="Rohan Neure, performance and growth marketer behind GrowthLabs" width={1089} height={1089} sizes="(max-width: 1024px) 80vw, 32vw" priority /></figure>
      </div>
      <div className="flex flex-col gap-3 sm:flex-row"><Link className="button button-primary" href={siteConfig.cta.primary.href}>{siteConfig.cta.primary.label}<Arrow /></Link><Link className="button" href={siteConfig.cta.secondary.href}>{siteConfig.cta.secondary.label}<Arrow /></Link></div>
    </section>

    <section className="section"><div className="shell"><SectionHeading eyebrow="One connected system" title="Stop losing customers after the click." copy="GrowthLabs by Rohan Neure connects SEO, paid ads, content, websites, CRO, and tracking around one goal: turning attention into real business." /><ul className="mt-12 grid gap-5 border-t border-[var(--line)] pt-6 md:ml-[25%] md:grid-cols-2"><li>Get found by customers ready to act.</li><li>Turn paid clicks into qualified enquiries.</li><li>Convert more of the traffic you already have.</li><li>Know what creates actual business growth.</li></ul></div></section>

    <section className="section"><div className="shell"><SectionHeading eyebrow="Common problems we fix" title="Why digital marketing fails to convert." copy="Businesses rarely need another disconnected post, blog, or ad. They need search, content, campaigns, websites, and tracking to turn attention into trust—and trust into action." /><div className="mt-16 grid gap-x-8 gap-y-12 md:grid-cols-2">{problems.map((item, index) => <article className="card" key={item.title}><p className="eyebrow">0{index + 1}</p><h3 className="mt-5 font-serif text-3xl tracking-[-.035em]">{item.title}</h3><p className="mt-4 max-w-xl leading-7 text-[var(--muted)]">{item.copy}</p></article>)}</div></div></section>

    <section className="section bg-[linear-gradient(135deg,#21170d,#4a2005)] text-[var(--paper)]"><div className="shell"><SectionHeading eyebrow="Services" title="Search, leads, and growth—not basic execution." copy="Every service is planned around business goals, search demand, audience intent, content quality, landing-page performance, and measurable outcomes." /><div className="mt-16 grid gap-10 md:grid-cols-2">{services.map((service, index) => <article className="border-t border-white/30 pt-5" key={service.slug}><div className="flex justify-between gap-4"><p className="eyebrow !text-[var(--sun)]">0{index + 1}</p><span aria-hidden="true" className="text-white/35">↗</span></div><h3 className="mt-6 font-serif text-3xl tracking-[-.035em]">{service.title}</h3><p className="mt-4 max-w-xl leading-7 text-white/65">{service.summary}</p></article>)}</div><div className="mt-12 flex flex-col gap-3 sm:flex-row"><Link className="button border-white text-white hover:bg-white hover:text-[var(--ink)]" href="/services">Explore all services <Arrow /></Link><Link className="button border-white/40 text-white hover:bg-white hover:text-[var(--ink)]" href="/seo-expert-in-nepal">SEO expert in Nepal <Arrow /></Link><Link className="button border-white/40 text-white hover:bg-white hover:text-[var(--ink)]" href="/seo-company-in-nepal">SEO company in Nepal <Arrow /></Link></div></div></section>

    <section className="section"><div className="shell"><div className="warm-panel grid gap-8 p-6 md:grid-cols-[1fr_3fr] md:p-12"><p className="eyebrow">Working stack</p><div><h2 className="section-title">Tools are useful. The system matters more.</h2><p className="lede mt-6">Research, acquisition, measurement, behaviour, reporting, and optimisation connected through a practical working stack.</p><ul className="mt-9 flex flex-wrap gap-2">{tools.map((tool) => <li className="rounded-full border border-[color:color-mix(in_srgb,var(--accent)_24%,var(--line))] bg-white/65 px-4 py-2 text-sm font-semibold" key={tool}>{tool}</li>)}</ul></div></div></div></section>

    <section className="section"><div className="shell"><SectionHeading eyebrow="Selected experience" title="Founder-led, backed by real execution." copy="The supplied experience spans international websites, organic search, paid media, and local growth." /><div className="mt-14 grid gap-8 md:grid-cols-2 lg:grid-cols-4">{proofPoints.map((item) => <article className="card" key={item.metric}><p className="font-serif text-5xl tracking-[-.05em] text-[var(--accent)]">{item.metric}</p><h3 className="mt-2 font-bold">{item.label}</h3><p className="mt-4 text-sm leading-6 text-[var(--muted)]">{item.detail}</p></article>)}</div></div></section>

    <section className="section"><div className="shell"><SectionHeading eyebrow="Search performance" title="Evidence in the direction of travel." copy="Selected Google Search Console captures supplied from active work. Each view shows a different search property and reporting window; they are presented without implying that every engagement produces the same outcome." /><div className="mt-14 grid gap-8 md:grid-cols-2">{siteConfig.proofImages.map((item) => <figure className="card" key={item.src}><div className="overflow-hidden border border-[var(--line)] bg-white"><Image className="h-auto w-full" src={item.src} alt={item.alt} width={2275} height={1040} sizes="(max-width: 768px) 100vw, 50vw" /></div><figcaption className="mt-3 text-xs leading-5 text-[var(--muted)]">{item.caption}</figcaption></figure>)}</div></div></section>

    <section className="section"><div className="shell"><SectionHeading eyebrow="Who we help" title="Built for businesses with something real to grow." copy="GrowthLabs works best with teams that need clearer positioning, stronger visibility, better leads, and a structured digital growth system." /><div className="mt-14 grid gap-8 sm:grid-cols-2 lg:grid-cols-3">{industries.map((industry) => <article className="card" key={industry.title}><h3 className="font-serif text-2xl">{industry.title}</h3><p className="mt-3 text-sm leading-6 text-[var(--muted)]">{industry.copy}</p></article>)}</div></div></section>

    <section className="section"><div className="shell"><SectionHeading eyebrow="The process" title="Clarity before execution." copy="A practical sequence that makes it clear what is being done, why it matters, and what should happen next." /><ol className="mt-14 md:ml-[25%]">{process.map((step, index) => <li className="grid gap-3 border-t border-[var(--line)] py-6 sm:grid-cols-[4rem_1fr_2fr]" key={step.title}><span className="eyebrow">0{index + 1}</span><h3 className="font-serif text-2xl">{step.title}</h3><p className="leading-7 text-[var(--muted)]">{step.copy}</p></li>)}</ol></div></section>

    <section className="section"><div className="shell"><SectionHeading eyebrow="FAQ" title="Useful answers before the first call." /><div className="mt-14 md:ml-[25%]">{faqs.map((item) => <details className="group border-t border-[var(--line)] py-5" key={item.question}><summary className="flex cursor-pointer list-none items-center justify-between gap-6 font-serif text-xl"><span>{item.question}</span><span aria-hidden="true" className="text-[var(--accent)] group-open:rotate-45">+</span></summary><p className="prose-copy mt-4 pr-8">{item.answer}</p></details>)}</div></div></section>
    <ContactCta />
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema).replace(/</g, "\\u003c") }} />
  </>;
}
