import type { InsightArticle } from "./insights";

const published = "2026-09-01";

export const authorityInsights: InsightArticle[] = [
  {
    slug: "technical-seo-audit-checklist",
    category: "SEO",
    title: "Technical SEO audit: a crawl-to-conversion framework and checklist",
    shortTitle: "Technical SEO audit framework",
    metaTitle: "Technical SEO Audit: Framework, Steps & Checklist",
    description: "Run a technical SEO audit across crawling, indexing, canonicals, architecture, rendering, performance, structured data and conversion paths with a prioritised framework.",
    primaryKeyword: "technical SEO audit",
    supportingKeywords: ["technical SEO audit checklist", "website SEO audit", "SEO site audit", "crawl audit", "indexing audit", "technical SEO services"],
    answer: "A technical SEO audit tests whether search engines can reliably discover, crawl, render, understand and index the intended version of each valuable page. A commercially useful audit then connects those findings to internal navigation, search intent, page experience and conversion paths so fixes are prioritised by impact rather than tool severity alone.",
    summaryPoints: [
      "Audit the discovery-to-conversion chain, not an isolated list of tool warnings.",
      "Separate crawling, indexing, canonicalisation and ranking because each is a different system state.",
      "Validate templates and page groups at scale, then manually inspect representative URLs.",
      "Prioritise by affected demand, page value, scale, confidence, effort and dependency.",
    ],
    datePublished: published,
    dateModified: published,
    readingTime: "14 min read",
    sections: [
      {
        id: "scope",
        title: "What a technical SEO audit should answer",
        answer: "The audit should explain which valuable pages search systems can reach and index, which version they interpret as canonical, what prevents understanding or usability, and which repairs deserve implementation first.",
        paragraphs: [
          "Begin with the business model, priority offers, target markets and page types. A blocked checkout, service template or location cluster can matter more than hundreds of harmless parameter URLs. The audit therefore needs commercial context before a crawler is configured.",
          "Record the production host, protocol, preferred hostname, important subdomains, rendering method, content system, international variants and recent migrations. This baseline prevents a correct technical observation from becoming the wrong business recommendation.",
        ],
        bullets: ["Priority pages and template groups", "Organic demand and conversion role", "Known migrations, redesigns and platform changes", "Analytics, Search Console, server-log and CMS access", "Teams that own code, content, design and release approval"],
      },
      {
        id: "pipeline",
        title: "Follow the crawl, render, index and canonical pipeline",
        paragraphs: [
          "Discovery normally begins through crawlable links, submitted sitemaps and URLs already known to the search engine. A URL can be discovered but blocked from crawling, crawled but not rendered usefully, rendered but excluded from indexing, or indexed under a different canonical. Treating all four states as a single indexability score hides the real cause.",
          "Robots.txt manages crawler access; it is not a reliable instruction for keeping a URL out of search. For pages that should not appear, use an appropriate noindex instruction while allowing Google to crawl it, or protect private material with authentication. Google also describes canonical signals as hints rather than absolute rules, so internal links, redirects, sitemaps and canonical tags should agree.",
        ],
        table: {
          caption: "Technical SEO state and the question it answers",
          headers: ["State", "Audit question", "Evidence to inspect"],
          rows: [
            ["Discovery", "Can a crawler find the preferred URL?", "Internal links, orphan reports, XML sitemaps"],
            ["Crawling", "Is access allowed and efficient?", "Robots rules, status codes, logs, crawl reports"],
            ["Rendering", "Does the rendered page expose the useful content and links?", "Rendered HTML, resources, hydration and console failures"],
            ["Indexing", "Is the page eligible and selected for indexing?", "Noindex, quality, duplicates, Search Console inspection"],
            ["Canonicalisation", "Which URL represents the content set?", "Canonicals, redirects, links, sitemap and Google-selected canonical"],
          ],
        },
      },
      {
        id: "process",
        title: "The 10-step technical SEO audit process",
        steps: [
          { title: "Define valuable page groups", copy: "Map services, products, locations, resources and conversion pages to templates and intended search demand." },
          { title: "Verify hosts and redirects", copy: "Test HTTP, HTTPS, www, non-www, trailing-slash and known legacy variants for one consistent destination." },
          { title: "Crawl like a search engine", copy: "Use a controlled crawl, inspect linked and orphan URLs, and compare the result with sitemaps, analytics and Search Console." },
          { title: "Classify status codes", copy: "Find broken internal links, redirect chains, soft errors, unstable responses and server failures by template and importance." },
          { title: "Test directives and canonicals", copy: "Compare robots access, robots meta, X-Robots-Tag, canonical tags, redirects and Google-selected canonicals." },
          { title: "Inspect rendering", copy: "Compare source and rendered output, important resources, navigation, lazy loading and client-side error states." },
          { title: "Review architecture", copy: "Measure click paths, breadcrumbs, contextual links, pagination and whether important pages receive descriptive internal links." },
          { title: "Evaluate page experience", copy: "Inspect responsive layout, interaction, Core Web Vitals evidence, accessibility fundamentals and intrusive friction." },
          { title: "Validate metadata and structured data", copy: "Check unique titles, descriptions, headings, visible entity facts and markup eligibility against page content." },
          { title: "Prioritise and regression-test", copy: "Turn findings into owned tickets with evidence, acceptance criteria, dependencies and pre/post-release validation." },
        ],
      },
      {
        id: "architecture",
        title: "Audit information architecture and internal links",
        paragraphs: [
          "A technically indexable page can still be weakly connected. Important pages should appear in useful navigation, category or hub structures and contextual links where the reader naturally needs the next answer. Descriptive anchor text helps people and search systems understand that relationship.",
          "Look for orphan pages, competing URLs, infinite filters, broken pagination, inconsistent breadcrumbs and important content buried behind site search or JavaScript-only controls. The goal is not a universal three-click rule; it is a clear hierarchy that reflects customer decisions and concentrates internal authority around canonical pages.",
        ],
        callout: "Do not create internal links merely to repeat a keyword. Place a link when its destination completes the current task or supports the next decision.",
      },
      {
        id: "experience",
        title: "Rendering, performance and page-experience checks",
        bullets: [
          "Confirm primary copy, links, images, forms and structured data are available in the rendered experience.",
          "Test representative templates on small mobile, tablet and desktop viewports rather than one homepage score.",
          "Use field data where available; lab tests help reproduce problems but do not describe every visitor.",
          "Reserve media dimensions, optimise delivery, reduce unnecessary scripts and test real interaction states.",
          "Check keyboard access, visible focus, labels, contrast, zoom, reduced motion and error recovery.",
        ],
        paragraphs: ["Performance is a user and conversion concern as well as a technical search concern. Diagnose the responsible template, component, asset or third-party script before prescribing generic compression or dependency removal."],
      },
      {
        id: "prioritisation",
        title: "Prioritise fixes by business and search impact",
        table: {
          caption: "A practical technical SEO priority model",
          headers: ["Factor", "Question", "Higher-priority signal"],
          rows: [
            ["Value", "Does the issue affect an important journey?", "Revenue, lead, product or high-demand pages"],
            ["Scale", "How many useful URLs or templates are affected?", "Systemic template or navigation failure"],
            ["Severity", "What state does it prevent?", "Discovery, access, indexing or conversion blocked"],
            ["Confidence", "How strong is the evidence?", "Reproduced issue with corroborating data"],
            ["Effort", "What must change and who owns it?", "High-impact fix with limited dependencies"],
            ["Risk", "Could implementation create regressions?", "Migration, canonical, redirect or rendering change"],
          ],
        },
        callout: "A crawler's critical label is not the implementation priority. Attach affected URLs, screenshots or response evidence, the expected state, owner and validation method to every ticket.",
      },
      {
        id: "verification",
        title: "Verify the release instead of closing the ticket",
        steps: [
          { title: "Test before release", copy: "Validate the fix in an environment that reflects production behaviour and includes representative templates." },
          { title: "Re-crawl the changed scope", copy: "Confirm status codes, directives, canonicals, rendering and internal links now match the acceptance criteria." },
          { title: "Inspect production URLs", copy: "Check actual responses, rendered content, analytics events, forms and search-engine inspection evidence." },
          { title: "Monitor the expected signal", copy: "Track coverage, crawling, impressions, qualified visits and conversions on a timeframe appropriate to the change." },
        ],
      },
    ],
    faqs: [
      { question: "What is a technical SEO audit?", answer: "It is a structured evaluation of how a website supports discovery, crawling, rendering, indexing, canonicalisation, understanding, page experience and conversion across its valuable page groups." },
      { question: "How often should a technical SEO audit be completed?", answer: "Use continuous monitoring for critical failures and a deeper audit before and after migrations, redesigns, major template changes or when evidence shows organic performance and index coverage have changed." },
      { question: "Which technical SEO audit tool is best?", answer: "No single tool represents the complete system. Combine a crawler with Search Console, analytics, URL inspection, browser rendering, performance evidence, server logs where available and manual journey testing." },
      { question: "Does robots.txt remove a page from Google?", answer: "No. Robots.txt controls crawling, not guaranteed indexing. Google recommends noindex for eligible public URLs that should not appear, or authentication for private content." },
      { question: "How long does a technical SEO audit take?", answer: "It depends on site size, rendering, templates, markets, historical migrations, access and the depth of manual validation. Scope by page systems and business risk rather than promising a universal duration." },
    ],
    related: [
      { label: "SEO audit services in Nepal", href: "/seo-audit-services-in-nepal", copy: "Turn the framework into an owned implementation roadmap." },
      { label: "SEO audit checklist", href: "/resources/seo-audit-checklist", copy: "Download the practical audit worksheet." },
      { label: "Website launch checklist", href: "/resources/website-launch-checklist", copy: "Prevent migration and release regressions." },
    ],
    sources: [
      { label: "Crawling and indexing overview", publisher: "Google Search Central", href: "https://developers.google.com/search/docs/crawling-indexing", usedFor: "Discovery, crawling, rendering and indexing distinctions" },
      { label: "Canonicalization", publisher: "Google Search Central", href: "https://developers.google.com/search/docs/crawling-indexing/canonicalization", usedFor: "Canonical signals and duplicate URL handling" },
      { label: "Build and submit a sitemap", publisher: "Google Search Central", href: "https://developers.google.com/search/docs/crawling-indexing/sitemaps/build-sitemap", usedFor: "Absolute canonical sitemap URL guidance" },
      { label: "SEO Starter Guide", publisher: "Google Search Central", href: "https://developers.google.com/search/docs/fundamentals/seo-starter-guide", usedFor: "Site organisation, links and search fundamentals" },
    ],
    download: { label: "Download the SEO audit checklist", href: "/downloads/growthlabs-seo-audit-checklist.csv", description: "A reusable CSV for technical, content, local and conversion checks." },
    cta: { title: "Need priorities your team can actually implement?", copy: "Share the domain, priority offers and recent site changes. We will identify the technical, content and conversion constraints that deserve inspection first.", label: "Request a technical SEO review", href: "/contact" },
  },
  {
    slug: "google-ads-conversion-tracking-guide",
    category: "Paid media",
    title: "Google Ads conversion tracking: architecture, setup and QA guide",
    shortTitle: "Google Ads conversion tracking",
    metaTitle: "Google Ads Conversion Tracking: Setup & QA Guide",
    description: "Plan Google Ads conversion tracking across tags, GA4, enhanced conversions, offline outcomes, consent, attribution and quality assurance without optimising for the wrong event.",
    primaryKeyword: "Google Ads conversion tracking",
    supportingKeywords: ["Google Ads conversion setup", "enhanced conversions", "Google Tag Manager conversion tracking", "offline conversion tracking", "Google Ads tracking audit"],
    answer: "Google Ads conversion tracking records valuable actions after advertising interactions so campaigns can be measured and, where configured, optimised toward those actions. A reliable setup defines the business outcome first, assigns one source of truth to each action, captures consented signals correctly, prevents duplicates and tests the complete path from ad click to qualified lead or sale.",
    summaryPoints: ["Define qualified business outcomes before creating tags.", "Keep action names, sources, values and optimisation roles unambiguous.", "Use enhanced conversions only with appropriate consent, disclosure and compliant first-party data.", "QA browser events, platform diagnostics and downstream lead or revenue quality."],
    datePublished: published,
    dateModified: published,
    readingTime: "13 min read",
    sections: [
      { id: "measurement-plan", title: "Start with a conversion measurement plan", answer: "Write the outcome, trigger, owner, data source, value, deduplication key and optimisation role before implementation.", paragraphs: ["A click, page view or button tap may be useful for diagnosis, but it is not automatically a business conversion. Separate micro-actions such as engaged visits from macro outcomes such as qualified enquiries, purchases or accepted opportunities.", "Map the customer journey beyond the browser. If the business closes by phone, WhatsApp, CRM or offline sales, website-only tracking can reward campaigns that generate submissions while hiding lead quality and revenue."], table: { caption: "Conversion action planning model", headers: ["Action", "Business meaning", "Recommended use"], rows: [["Qualified form enquiry", "Required details submitted and valid", "Primary when it represents a real sales handoff"], ["Phone call", "Call meets an agreed duration or quality condition", "Primary or secondary based on validation"], ["Purchase", "Confirmed transaction with accurate value", "Primary revenue outcome"], ["CRM opportunity or sale", "Lead progresses to a defined offline stage", "Import for quality and value feedback"], ["Page engagement", "Visitor reaches a diagnostic milestone", "Observation, not a substitute for the outcome"]] } },
      { id: "architecture", title: "Choose the right source for each action", paragraphs: ["Google Ads tags can measure website actions directly. GA4 key events can also be imported when cross-channel analysis needs a shared event definition. Avoid counting both versions of the same action as separate primary outcomes unless the measurement design deliberately handles duplication.", "Document the tag or event owner, account link, attribution setting, value rule, currency, counting method and reporting latency. Naming conventions should distinguish platform, market, action and qualification stage."], bullets: ["Website tag or Google Tag Manager event", "GA4 event imported to Google Ads", "Phone-call conversion where supported", "Offline conversion or CRM lifecycle import", "App conversion through the appropriate analytics stack"] },
      { id: "implementation", title: "Nine-step Google Ads tracking setup", steps: [
        { title: "Define the qualified action", copy: "Agree the exact customer behaviour and what makes it commercially valid." },
        { title: "Choose one event source", copy: "Select Google Ads, GA4 or an offline source for each action and document why." },
        { title: "Specify the trigger", copy: "Use a confirmed success state or reliable data event, not an unverified button click." },
        { title: "Plan values and currency", copy: "Send real revenue when available or an evidence-based value model with clear limitations." },
        { title: "Preserve click identifiers", copy: "Retain required click and campaign identifiers through the journey where lawful and technically supported." },
        { title: "Configure consent", copy: "Align collection, storage and advertising use with the applicable consent and privacy requirements." },
        { title: "Add enhanced conversions", copy: "Where appropriate, send properly normalised and hashed first-party data using Google's supported method." },
        { title: "Test and deduplicate", copy: "Validate one intended conversion per qualifying action across browsers, devices and repeated states." },
        { title: "Inspect diagnostics and business data", copy: "Confirm platform receipt, reporting behaviour and whether resulting leads or sales are genuinely qualified." },
      ] },
      { id: "enhanced", title: "Enhanced conversions and first-party data", paragraphs: ["Enhanced conversions supplement existing conversion tags with consented first-party data such as an email address or phone number, transformed using SHA-256 before transmission through supported implementations. They are intended to improve observable conversion matching, not replace a sound base event.", "Google consolidated enhanced conversions for web and leads into a unified setting during 2026. Existing implementations should be reviewed against the current Google Ads interface and diagnostics rather than copied from an older tutorial."], callout: "Hashing does not remove privacy responsibility. Obtain appropriate consent, update disclosures, limit data to the defined purpose and follow Google policies and applicable law." },
      { id: "qa", title: "QA the complete conversion path", table: { caption: "Google Ads tracking quality assurance", headers: ["Layer", "Test", "Failure signal"], rows: [["Browser", "Trigger fires only after success", "Page view or click counted without completion"], ["Tag manager", "Correct ID, label, value and currency", "Wrong environment, stale container or undefined values"], ["Network", "One expected request is sent", "Duplicate requests or blocked dependencies"], ["Google Ads", "Diagnostics show recent valid activity", "Inactive, unverified or unexpected action source"], ["Business", "CRM or sales outcome matches intent", "Cheap conversions with low contact or close quality"]] } },
      { id: "offline", title: "Close the loop with qualified offline outcomes", paragraphs: ["Capture the advertising click identifier and first-party lead identifiers through the form or sales process, then return meaningful stages such as qualified lead, opportunity or completed sale using a supported import. Use stable transaction or order identifiers for deduplication.", "Google has been transitioning offline data workflows toward its Data Manager API in 2026. Confirm the current supported integration before building a new upload process, especially if an older tutorial refers to deprecated endpoints."], bullets: ["Define lifecycle stages with sales", "Store identifiers securely and lawfully", "Upload within supported windows", "Use consistent timezone, value and currency", "Reconcile accepted, rejected and duplicate records"] },
      { id: "decisions", title: "Use tracking to improve decisions, not decorate reports", paragraphs: ["A conversion total should change a decision: search-term exclusions, bid strategy, budget, audience, message, landing page, sales follow-up or offer. Review lag, attribution, consent coverage and imported-stage volume before interpreting short periods.", "Pair platform reporting with landing-page behaviour, call quality, CRM progression, revenue and contribution. A campaign with fewer reported leads can be more valuable when those leads are more relevant and more likely to close."], callout: "Do not optimise bidding toward an event merely because it fires frequently. Optimise toward the strongest outcome that produces enough reliable data for the decision being made." },
    ],
    faqs: [
      { question: "What is Google Ads conversion tracking?", answer: "It is the measurement setup that records valuable actions associated with Google Ads interactions, such as purchases, qualified enquiries, calls or imported offline outcomes." },
      { question: "Should I use Google Ads tracking or import GA4 conversions?", answer: "Choose per action. Direct Ads tags can support advertising-specific measurement; GA4 imports can align cross-channel events. Avoid duplicate primary actions and document the source of truth." },
      { question: "Why is my Google Ads conversion not recording?", answer: "Check the conversion ID and label, trigger condition, consent state, tag publication, success event, network request, browser restrictions, account action status and reporting delay." },
      { question: "What are enhanced conversions?", answer: "They use properly transformed first-party customer data collected during a conversion to improve matching with signed-in Google accounts, subject to consent, policy and legal requirements." },
      { question: "Can Google Ads tracking show actual sales?", answer: "Yes when purchases include accurate values or when qualified CRM and offline sales outcomes are imported through a supported setup. Platform reports still require reconciliation with business records." },
    ],
    related: [
      { label: "Analytics and conversion tracking", href: "/analytics-conversion-tracking-services", copy: "Build and audit the complete measurement system." },
      { label: "Google Ads agency in Nepal", href: "/google-ads-agency-in-nepal", copy: "Connect tracking to search demand and landing pages." },
      { label: "Google Ads break-even calculator", href: "/tools/google-ads-break-even-calculator", copy: "Model affordable CPC and CPA assumptions." },
    ],
    sources: [
      { label: "About enhanced conversions", publisher: "Google Ads Help", href: "https://support.google.com/google-ads/answer/10868881", usedFor: "Enhanced conversion purpose and hashed first-party data" },
      { label: "Enhanced conversions best practices", publisher: "Google Ads Help", href: "https://support.google.com/google-ads/answer/14795081", usedFor: "Implementation and diagnostic guidance" },
      { label: "2026 enhanced conversions updates", publisher: "Google Ads Help", href: "https://support.google.com/google-ads/answer/16884284", usedFor: "Unified settings and offline workflow changes" },
      { label: "Enhanced conversions in Google Analytics", publisher: "Google Analytics Help", href: "https://support.google.com/analytics/answer/14252663", usedFor: "GA4-based enhanced conversion context" },
    ],
    cta: { title: "Are campaigns optimising toward the right outcome?", copy: "Share the active account, conversion actions, website journey and lead-quality process. We will identify the event, consent, duplication or feedback gap worth fixing first.", label: "Request a tracking review", href: "/contact" },
  },
  {
    slug: "meta-ads-creative-testing-framework",
    category: "Paid media",
    title: "Meta Ads creative testing: a hypothesis-led framework for better decisions",
    shortTitle: "Meta Ads creative testing",
    metaTitle: "Meta Ads Creative Testing Framework & Tracker",
    description: "Build a Meta Ads creative testing system across audience insight, hooks, angles, proof, formats, offers, landing-page continuity, measurement and iteration.",
    primaryKeyword: "Meta Ads creative testing",
    supportingKeywords: ["Facebook Ads creative testing", "Meta Ads testing framework", "ad creative strategy", "Meta creative test", "Instagram Ads creative"],
    answer: "Meta Ads creative testing is the controlled process of comparing meaningful message, format or execution hypotheses to learn what helps a defined audience notice, understand, believe and act. A useful test records the hypothesis, controls avoidable differences, measures the complete conversion path and turns the result into a clear scale, iterate, pause or retest decision.",
    summaryPoints: ["Test a customer or message hypothesis, not a random visual change.", "Separate hooks, angles, proof, offers, formats and calls to action in the test plan.", "Judge creative through qualified business outcomes as well as platform response.", "Record what changed, what the evidence suggests and what the next variant should learn."],
    datePublished: published,
    dateModified: published,
    readingTime: "12 min read",
    sections: [
      { id: "strategy", title: "Creative testing is a learning system", answer: "The purpose is to reduce uncertainty about the audience, message and action, not to produce a folder of ads.", paragraphs: ["Start with the commercial job: introduce a problem, create desire, explain an offer, answer an objection, retarget existing interest or convert a high-intent audience. The same creative cannot be judged sensibly without its job, objective and destination.", "Write the hypothesis in plain language: for this audience and awareness stage, this problem framing or proof should improve this defined response because of this customer insight. Then decide which part of the creative carries that hypothesis."], callout: "A colour change is not a strategy unless colour is the specific barrier being tested. Prioritise differences a customer can understand and respond to." },
      { id: "variables", title: "Build a creative variable matrix", table: { caption: "Meta Ads creative variables and the question each tests", headers: ["Variable", "Question", "Example direction"], rows: [["Hook", "What earns the next second of attention?", "Problem, outcome, contrast or direct qualification"], ["Angle", "Which reason to care is strongest?", "Speed, control, risk, convenience or economics"], ["Proof", "What makes the claim believable?", "Demonstration, process, verified evidence or customer voice"], ["Offer", "Why act now or continue?", "Audit, trial, consultation, product or clear next step"], ["Format", "How should the message be experienced?", "Founder video, demo, static, carousel or testimonial"], ["CTA", "What exact action follows?", "Learn, compare, calculate, enquire or purchase"]] } },
      { id: "process", title: "Seven steps for a controlled Meta creative test", steps: [
        { title: "Choose the decision", copy: "State what the team will change if one hypothesis receives stronger qualified evidence." },
        { title: "Define the audience context", copy: "Record market, awareness, pain, objection, current belief and the offer being evaluated." },
        { title: "Write the hypothesis", copy: "Connect one meaningful creative difference to an expected audience response and reason." },
        { title: "Create distinct variants", copy: "Make the intended difference visible while controlling avoidable production and destination changes." },
        { title: "Set measurement rules", copy: "Choose delivery, attention, click, page, conversion and qualified-outcome signals before launch." },
        { title: "Allow an interpretable comparison", copy: "Avoid constant edits and fragmented budgets; record delivery differences and material platform changes." },
        { title: "Decide and document", copy: "Scale, iterate, pause or retest with the evidence, limitations and next learning question." },
      ] },
      { id: "native", title: "Design for placement without losing the message", paragraphs: ["Meta describes Reels ads as built-for-mobile placements and recommends native vertical creative with key messages inside safe zones and suitable audio. Placement asset customisation can adapt creative, but automation should be reviewed so crops, generated extensions or music do not change the offer or obscure essential information.", "Create a master message system, then adapt the composition, pace, captions and safe-zone placement for each eligible experience. The opening frame should establish relevance quickly, while the complete ad must still communicate the offer, proof and next action without relying on audio alone."], bullets: ["Use legible on-screen text and captions", "Protect logos, faces, proof and CTA from interface overlays", "Check 9:16, 1:1 and 4:5 crops where used", "Preview every selected placement", "Retain brand and landing-page continuity"] },
      { id: "measurement", title: "Read the metric chain, not one winning number", table: { caption: "Creative performance diagnostic chain", headers: ["Stage", "Signal", "What it may suggest"], rows: [["Delivery", "Reach, frequency, CPM", "Auction access and audience saturation context"], ["Attention", "Video retention or meaningful engagement", "Hook and format response"], ["Interest", "Outbound clicks and landing-page views", "Message and offer curiosity"], ["Experience", "Page engagement and form progression", "Ad-to-page continuity and friction"], ["Outcome", "Qualified leads, purchases, revenue", "Commercial usefulness"], ["Learning", "Result by hypothesis and segment", "What to scale, adapt or test next"]] }, paragraphs: ["No universal CTR, hook-rate or frequency benchmark proves creative quality. Compare against the campaign job, market, format, historical baseline, spend, attribution and downstream customer evidence."] },
      { id: "diagnosis", title: "Diagnose creative and journey problems separately", bullets: ["High attention but weak clicks can indicate entertainment without a relevant offer.", "Clicks without landing-page views can indicate slow pages, accidental interaction or measurement gaps.", "Page visits without conversion can indicate message mismatch, weak proof, price or form friction.", "Cheap leads with low contactability can indicate overpromising, insufficient qualification or accidental submissions.", "Strong lead quality with limited volume can justify testing broader hooks or distribution before changing the core offer."], callout: "Do not declare the creative a failure when the destination, tracking or follow-up breaks the expectation it created." },
      { id: "iteration", title: "Turn a winner into the next learning cycle", paragraphs: ["A winning ad is temporary evidence in a specific audience, market, budget and time period. Preserve its core hypothesis, then create adjacent variants that test the next most important uncertainty: a new hook for the same angle, stronger proof for the same offer, or a native format for another placement.", "Keep a creative ledger with asset ID, audience, objective, hypothesis, variables, dates, spend, delivery, conversions, qualified outcomes, decision and next test. This protects institutional learning when people, campaigns or account structures change."], steps: [{ title: "Scale carefully", copy: "Increase exposure while watching delivery, frequency and qualified economics." }, { title: "Iterate the mechanism", copy: "Keep the reason the creative worked and change one adjacent decision variable." }, { title: "Refresh before exhaustion", copy: "Prepare related concepts rather than waiting for visible decline." }, { title: "Archive the learning", copy: "Record why the variant won, its limits and where it should not be reused." }] },
    ],
    faqs: [
      { question: "What is creative testing in Meta Ads?", answer: "It is a structured comparison of meaningful ad hypotheses, such as hooks, messages, proof, offers or formats, to learn what produces a stronger defined audience and business response." },
      { question: "How many Meta ad creatives should I test?", answer: "There is no universal number. Use the smallest set that tests the highest-value hypotheses without fragmenting the available budget and evidence." },
      { question: "Should I test one variable at a time?", answer: "Use controlled single-variable tests when isolating cause matters. Use deliberately different concepts when the decision is which complete message direction deserves investment. Document the test type." },
      { question: "How long should a Meta creative test run?", answer: "Long enough to collect interpretable evidence across delivery and qualified outcomes without constant edits. The period depends on budget, audience, conversion volume, sales lag and decision risk." },
      { question: "What makes a good Reels ad creative?", answer: "A clear audience-relevant message delivered in a native vertical experience, with legible safe-zone content, suitable audio or captions, credible proof and continuity with the destination." },
    ],
    related: [
      { label: "Meta Ads agency in Nepal", href: "/meta-ads-agency-in-nepal", copy: "Connect creative learning to campaigns and lead quality." },
      { label: "Meta creative testing tracker", href: "/resources/meta-ads-creative-testing-tracker", copy: "Download the hypothesis and result ledger." },
      { label: "Meta Ads budget planner", href: "/tools/meta-ads-budget-planner", copy: "Model a focused media scenario." },
    ],
    sources: [
      { label: "Instagram and Facebook Reels ads", publisher: "Meta for Business", href: "https://www.facebook.com/business/ads/facebook-instagram-reels-ads", usedFor: "Reels format, safe-zone, audio, placement and A/B testing guidance" },
      { label: "Lead ads", publisher: "Meta for Business", href: "https://www.facebook.com/business/ads/ad-objectives/lead-generation", usedFor: "Lead destination and campaign context" },
      { label: "Lead Ads documentation", publisher: "Meta for Developers", href: "https://developers.facebook.com/docs/marketing-api/guides/lead-ads/", usedFor: "Lead retrieval and system integration context" },
    ],
    download: { label: "Download the Meta creative tracker", href: "/downloads/growthlabs-meta-ads-creative-testing-tracker.csv", description: "Record hypotheses, controlled variables, evidence and next decisions." },
    cta: { title: "Need a creative system, not another batch of random ads?", copy: "Share the offer, audience, active creatives and qualified outcome. We will identify the message, format or journey hypothesis worth testing next.", label: "Request a Meta Ads review", href: "/contact" },
  },
  {
    slug: "local-seo-ranking-factors-guide",
    category: "Local SEO",
    title: "Local SEO ranking factors: relevance, distance and prominence explained",
    shortTitle: "Local SEO ranking factors",
    metaTitle: "Local SEO Ranking Factors: Complete Practical Guide",
    description: "Understand local SEO ranking factors across Google Business Profile, relevance, distance, prominence, reviews, categories, local pages, links and measurement.",
    primaryKeyword: "local SEO ranking factors",
    supportingKeywords: ["Google Maps ranking factors", "local search ranking", "Google Business Profile SEO", "local SEO guide", "rank higher on Google Maps"],
    answer: "Google says local results are mainly based on relevance, distance and prominence. Businesses improve the controllable parts by maintaining an eligible, verified and accurate Business Profile; choosing suitable categories; connecting consistent website and business information; earning genuine reviews and relevant links; publishing useful local pages; and making it easy for nearby customers to act.",
    summaryPoints: ["Relevance is the match between the search need and the business information Google understands.", "Distance depends on the searcher's location or the location implied by the query and cannot be optimised away.", "Prominence reflects how well-known the business appears through signals including links and reviews.", "There is no legitimate payment or request that buys a better organic local ranking."],
    datePublished: published,
    dateModified: published,
    readingTime: "13 min read",
    sections: [
      { id: "model", title: "The three-part local ranking model", table: { caption: "Google's local ranking factors", headers: ["Factor", "Meaning", "Controllable work"], rows: [["Relevance", "How well the profile matches the search", "Accurate categories, services, profile and website content"], ["Distance", "How far the business is from the searcher or implied location", "Accurate eligible location or service-area information"], ["Prominence", "How well-known the business appears", "Genuine reviews, relevant links, mentions and established information"]] }, paragraphs: ["These factors interact. A highly prominent business may appear across a wider area for some searches, while a nearby business can be more suitable for a location-sensitive need. No tool can report the private weighting for every query, person and map position."] },
      { id: "profile", title: "Build a complete, accurate Google Business Profile", steps: [
        { title: "Verify eligibility and ownership", copy: "Use the profile type, location and service-area configuration that truthfully represents how customers interact with the business." },
        { title: "Choose the primary category", copy: "Select the most specific available category that describes the main business, then use additional categories only for real operations." },
        { title: "Complete core information", copy: "Keep the name, address or service area, phone, website, hours and attributes accurate and current." },
        { title: "Describe real services", copy: "Add available services, products and factual business information without promotional stuffing or invented locations." },
        { title: "Maintain useful media", copy: "Publish authentic photographs and videos that help customers understand the location, people, work or experience." },
      ],
      callout: "Do not add keywords to the business name unless they are part of the real-world name. Misrepresentation creates policy and suspension risk." },
      { id: "categories", title: "Use categories, services and entities precisely", paragraphs: ["Google states that categories affect local ranking and recommends selecting a specific primary category. Category choice should reflect the core business, not every search phrase the business hopes to rank for.", "Reinforce the same entity on the website with accurate organisation, service, location and contact information. Service pages should explain what is offered, who it helps, the process, proof, constraints and the next step. Avoid creating thin pages for every neighbourhood when the business has no unique information or customer value for them."], bullets: ["One truthful primary business identity", "Specific eligible category", "Real additional categories and services", "Consistent name, phone, location and website", "Local page content that answers genuine local decisions"] },
      { id: "website", title: "Make the website support local understanding and conversion", paragraphs: ["The linked landing page should confirm the business, service, area served, contact routes, proof and policies a local customer needs. Use crawlable navigation, descriptive titles and headings, useful internal links and relevant local context.", "Structured data can describe visible facts but cannot create eligibility or replace the Business Profile. Keep LocalBusiness or the most specific valid type consistent with the page, address, telephone, opening hours and sameAs profiles. Never mark up reviews the business wrote about itself as independent review evidence."], bullets: ["Fast mobile access and tap-friendly contact routes", "Consistent location and service facts", "Dedicated pages for genuinely distinct services", "Directions or service-area context where useful", "Privacy-safe measurement for calls, messages and forms"] },
      { id: "reviews", title: "Build an honest review and response system", paragraphs: ["Google says more reviews and positive ratings can help local ranking and that useful replies help a business stand out. Ask real customers for honest feedback using the official review link or QR code at a natural point in the journey.", "Do not offer discounts, gifts or other incentives in exchange for reviews, changed reviews or removed negative feedback. Google describes incentivised review manipulation as fake and misleading content. Respond professionally, protect customer privacy and use recurring feedback themes to improve the operation."], steps: [{ title: "Choose the request moment", copy: "Ask after a completed, genuine customer experience." }, { title: "Make access simple", copy: "Use Google's review link or QR code without scripting the rating." }, { title: "Respond with context", copy: "Acknowledge useful details while avoiding private customer information." }, { title: "Learn from themes", copy: "Connect recurring praise or friction to service, page and operational changes." }] },
      { id: "prominence", title: "Develop local prominence beyond the profile", bullets: ["Earn links from relevant suppliers, associations, partners, publications and community resources when genuinely deserved.", "Keep core business information consistent across important industry and local directories.", "Publish original local expertise, guides, projects and evidence other organisations can reference.", "Build real partnerships and community participation rather than purchasing bulk citations.", "Monitor inaccurate duplicate listings and unauthorised profile changes."], paragraphs: ["Google notes that prominence can reflect links and reviews. The practical goal is not the largest citation count; it is a coherent and reputable footprint that helps customers and search systems verify the same business."] },
      { id: "measurement", title: "Measure local search without pretending every rank is fixed", table: { caption: "Local SEO measurement framework", headers: ["Layer", "Measure", "Interpretation"], rows: [["Visibility", "Relevant profile and page impressions", "Demand and local discoverability"], ["Actions", "Calls, directions, messages, website visits", "Intent signals, not confirmed customers"], ["Website", "Local organic entrances and conversions", "Page and journey contribution"], ["Business", "Qualified leads, appointments, visits and revenue", "Commercial outcome"], ["Reputation", "Review volume, recency, themes and response", "Customer evidence and operational insight"]] }, paragraphs: ["Results vary by location, device, query wording, time and search history. Use Search Console, Business Profile performance, analytics, call or CRM evidence and manual spot checks. Grid rank trackers can reveal patterns but should not be presented as a universal position."] },
      { id: "avoid", title: "Avoid local SEO shortcuts that create risk", bullets: ["Keyword-stuffed business names", "Fake locations, virtual offices or ineligible profiles", "Incentivised, purchased or employee-written reviews", "Mass-produced location pages with no unique value", "Bulk low-quality citations and irrelevant links", "False opening hours, categories, services or service areas"], callout: "Google states there is no way to request or pay for a better organic local ranking. Sustainable work improves accurate information, customer experience, relevance and reputation." },
    ],
    faqs: [
      { question: "What are the main local SEO ranking factors?", answer: "Google identifies relevance, distance and prominence as the main local ranking factors. Profile completeness, categories, reviews, links and accurate business information support the controllable parts." },
      { question: "How can I rank higher on Google Maps?", answer: "Verify and complete an eligible profile, choose accurate categories, maintain consistent information, publish helpful website content, earn genuine reviews and relevant links, and improve the customer journey. No action guarantees a position." },
      { question: "Do Google reviews help local SEO?", answer: "Google states that review quantity and positive ratings can help local ranking. Reviews must reflect genuine experiences and cannot be incentivised or purchased." },
      { question: "Does posting on Google Business Profile improve rankings?", answer: "Posts can communicate current information and support customer decisions, but Google does not list posting frequency as a direct local ranking factor. Prioritise accuracy and usefulness." },
      { question: "How long does local SEO take?", answer: "Timing depends on competition, proximity, profile history, website condition, review and link evidence, implementation speed and demand. Measure movement over an appropriate period rather than promise a fixed date." },
    ],
    related: [
      { label: "Local SEO services in Nepal", href: "/local-seo-services-in-nepal", copy: "Connect profile, website, reviews and measurement." },
      { label: "Google Business Profile optimisation", href: "/insights/google-business-profile-optimization", copy: "Work through the profile in practical detail." },
      { label: "Local SEO checklist", href: "/resources/local-seo-gbp-checklist", copy: "Download a repeatable local search review." },
    ],
    sources: [
      { label: "Tips to improve local ranking", publisher: "Google Business Profile Help", href: "https://support.google.com/business/answer/7091", usedFor: "Relevance, distance, prominence, completeness, reviews and ranking limits" },
      { label: "Manage your business category", publisher: "Google Business Profile Help", href: "https://support.google.com/business/answer/7249669", usedFor: "Primary category and category specificity" },
      { label: "Tips to get more reviews", publisher: "Google Business Profile Help", href: "https://support.google.com/business/answer/3474122", usedFor: "Genuine review requests, replies and incentive prohibition" },
      { label: "How Google sources local information", publisher: "Google Local Listings Help", href: "https://support.google.com/local-listings/answer/9851099", usedFor: "Business Profile, website, user and third-party information sources" },
    ],
    cta: { title: "Need a local search plan grounded in the real market?", copy: "Share the Business Profile, website, service area and highest-value local enquiries. We will identify the relevance, reputation, website or conversion gap worth addressing first.", label: "Request a local SEO review", href: "/contact" },
  },
];
