export type CommercialLanding = {
  slug: string;
  eyebrow: string;
  title: string;
  metaTitle: string;
  description: string;
  intro: string;
  promise: string;
  challenges: { title: string; copy: string }[];
  capabilities: { title: string; copy: string; items: string[] }[];
  outcomes: string[];
  process: { title: string; copy: string }[];
  faqs: { question: string; answer: string }[];
  related: { label: string; href: string }[];
};

const sharedProcess = [
  { title: "Diagnose", copy: "Review the offer, audience, current performance, competitors, customer journey, and measurement before prescribing channels." },
  { title: "Map the opportunity", copy: "Prioritise demand, pages, campaigns, creative, tracking, and conversion improvements around commercial value." },
  { title: "Build and launch", copy: "Create the agreed assets with a clear message, useful proof, focused calls to action, and reliable measurement." },
  { title: "Learn and improve", copy: "Use search, campaign, behaviour, and enquiry data to find friction and decide what deserves the next investment." },
];

export const commercialLandings: CommercialLanding[] = [
  {
    slug: "hotel-digital-marketing-agency", eyebrow: "Hospitality growth", title: "Hotel digital marketing built around direct demand and better booking journeys.", metaTitle: "Hotel Digital Marketing Agency | GrowthLabs Nepal", description: "Hotel digital marketing for Nepal hospitality brands through SEO, paid ads, social media, booking-focused pages, content, local search, tracking, and CRO.",
    intro: "GrowthLabs helps hotels connect discovery, destination research, local visibility, offers, paid campaigns, social proof, and booking-focused website experiences into one measurable system.", promise: "Reduce the distance between being discovered and receiving a qualified booking enquiry.",
    challenges: [{ title: "Dependence on marketplaces", copy: "Third-party platforms create reach, but a weak direct channel limits customer ownership and margin." }, { title: "Seasonal demand", copy: "Search, offers, content, and media need to anticipate demand windows rather than react after they begin." }, { title: "Beautiful site, unclear booking path", copy: "Guests need fast answers about rooms, location, experience, trust, availability, and the next step." }],
    capabilities: [{ title: "Hotel SEO", copy: "Build visibility around destination, property, experience, and high-intent accommodation searches.", items: ["Commercial keyword mapping", "Room and experience pages", "Local SEO", "Internal linking"] }, { title: "Demand campaigns", copy: "Match audience, season, creative, offer, and landing page across paid and social channels.", items: ["Google Ads", "Meta campaigns", "Retargeting", "Offer testing"] }, { title: "Booking CRO", copy: "Remove friction between interest and enquiry or booking.", items: ["Page hierarchy", "Trust signals", "Mobile journey", "Conversion tracking"] }],
    outcomes: ["Stronger direct-search visibility", "Clearer room and experience journeys", "Campaigns aligned to seasons and offers", "Measurable booking and enquiry paths"], process: sharedProcess,
    faqs: [{ question: "What does hotel digital marketing include?", answer: "It can include hotel SEO, local search, Google and Meta ads, social content, website and landing-page planning, offers, reputation signals, analytics, and booking conversion improvement." }, { question: "Can you market boutique hotels?", answer: "Yes. The plan is shaped around the property, destination, guest segments, experiences, seasonality, budget, and current booking journey rather than hotel size alone." }, { question: "Do you guarantee direct bookings?", answer: "No ethical agency can guarantee bookings. GrowthLabs improves the controllable system: visibility, targeting, message, offer, page experience, tracking, and iteration." }],
    related: [{ label: "SEO for travel agencies", href: "/seo-for-travel-agency" }, { label: "Digital marketing agency in Nepal", href: "/digital-marketing-agency-in-nepal" }]
  },
  {
    slug: "social-media-marketing-agency-in-nepal", eyebrow: "Social media / Nepal", title: "Social media marketing in Nepal that connects attention to action.", metaTitle: "Social Media Marketing Agency in Nepal | GrowthLabs", description: "GrowthLabs is a social media marketing agency in Nepal providing strategy, content direction, paid social, performance creative, landing pages, and measurement.",
    intro: "Build a social system around audience insight, content pillars, useful creative, campaign moments, proof, distribution, and a clear next step—not a posting quota.", promise: "Turn social activity into a coherent path from recognition to trust to enquiry.",
    challenges: [{ title: "Posting without a position", copy: "A busy calendar cannot replace a clear reason to follow, remember, and choose the brand." }, { title: "Creative without distribution", copy: "Organic and paid media need defined roles, audiences, formats, and learning loops." }, { title: "Engagement without measurement", copy: "Reach matters differently from qualified visits, leads, sales, and assisted conversions." }],
    capabilities: [{ title: "Strategy and planning", copy: "Define audiences, pillars, formats, campaign themes, and conversion routes.", items: ["Audience research", "Content pillars", "Campaign calendar", "Channel roles"] }, { title: "Creative direction", copy: "Plan hooks, formats, messages, proof, and calls to action for each stage.", items: ["Short-form direction", "Performance creative", "Offer communication", "Testing briefs"] }, { title: "Paid social", copy: "Connect Meta and TikTok media to appropriate offers and landing experiences.", items: ["Campaign structure", "Retargeting", "Lead generation", "Tracking"] }],
    outcomes: ["A clear editorial direction", "Creative designed for a purpose", "Organic and paid channels working together", "Reporting tied to useful actions"], process: sharedProcess,
    faqs: [{ question: "What does a social media marketing agency do?", answer: "A strong agency researches the audience, defines strategy, plans content, directs creative, manages distribution and paid media, measures behaviour, and improves the route to enquiry or sale." }, { question: "Do you offer social media packages?", answer: "Yes, but scope is based on the channels, strategy, creative workload, paid-media needs, approvals, community requirements, and measurement—not a generic number of posts." }, { question: "Do you manage Meta and TikTok ads?", answer: "GrowthLabs supports Meta and TikTok campaign planning, audience and offer strategy, performance creative direction, retargeting, lead generation, and conversion tracking." }],
    related: [{ label: "Social media package planning", href: "/social-media-marketing-packages" }, { label: "Advertising agency in Nepal", href: "/advertising-agency-in-nepal" }]
  },
  {
    slug: "web-design-company-in-nepal", eyebrow: "Web design / Nepal", title: "Web design in Nepal for trust, search visibility, and conversion.", metaTitle: "Web Design Company in Nepal | GrowthLabs", description: "Conversion-focused website design and development strategy in Nepal with SEO architecture, clear messaging, responsive UX, landing pages, speed, and measurement.",
    intro: "GrowthLabs plans websites as commercial systems: clear positioning, search-friendly structure, persuasive service pages, responsive experiences, proof, fast paths to action, and measurement from launch.", promise: "Create a website that explains the business clearly and gives every marketing channel somewhere strong to land.",
    challenges: [{ title: "Design before strategy", copy: "Visual polish cannot fix unclear positioning, missing pages, weak proof, or the wrong information architecture." }, { title: "SEO added at the end", copy: "Keywords, page intent, hierarchy, internal links, and technical foundations belong in the plan before build." }, { title: "No conversion path", copy: "Visitors need an obvious progression from understanding to confidence to action on every screen size." }],
    capabilities: [{ title: "Website strategy", copy: "Translate offers, audiences, search demand, and business goals into an intentional page system.", items: ["Discovery", "Sitemap", "Page intent", "Content hierarchy"] }, { title: "SEO architecture", copy: "Give important topics distinct homes and connect them through meaningful internal links.", items: ["Keyword mapping", "Metadata", "Semantic structure", "Technical SEO"] }, { title: "Conversion experience", copy: "Design for comprehension, credibility, speed, accessibility, and action.", items: ["Responsive UX", "Landing pages", "Trust and CTA planning", "Analytics readiness"] }],
    outcomes: ["A scalable page architecture", "Stronger service communication", "Responsive and accessible journeys", "SEO and measurement ready at launch"], process: sharedProcess,
    faqs: [{ question: "Do you provide web development in Nepal?", answer: "GrowthLabs provides website and landing-page strategy, UX and content structure, SEO architecture, conversion planning, and modern frontend implementation for agreed projects." }, { question: "Will the website be SEO-friendly?", answer: "The build plans crawlable pages, metadata, semantic headings, internal links, structured data where supported, responsive performance, sitemaps, robots rules, and clean URLs from the start." }, { question: "How much does a website cost?", answer: "Scope depends on page count, content readiness, integrations, design depth, functionality, migrations, and testing. A discovery review is needed before a responsible estimate." }],
    related: [{ label: "SEO company in Nepal", href: "/seo-company-in-nepal" }, { label: "Explore all services", href: "/services" }]
  },
  {
    slug: "seo-for-travel-agency", eyebrow: "Travel SEO", title: "SEO for travel agencies built around destinations, packages, and traveller intent.", metaTitle: "SEO for Travel Agencies | GrowthLabs Nepal", description: "Travel SEO strategy for agencies and tour companies: destination and package pages, keyword mapping, technical SEO, content clusters, internal links, and enquiry CRO.",
    intro: "Travel search is a network of destinations, seasons, itineraries, experiences, questions, and commercial comparisons. GrowthLabs turns that demand into a clear page and content architecture.", promise: "Help the right traveller find the right experience—and confidently take the next step.",
    challenges: [{ title: "Everything lives on one page", copy: "Distinct destinations, packages, activities, and traveller questions need an understandable hierarchy." }, { title: "Generic destination content", copy: "Useful pages answer planning questions while making the operator’s specific offer and next step clear." }, { title: "Seasonality is ignored", copy: "Search roadmaps should anticipate planning windows, regional demand, availability, and campaign timing." }],
    capabilities: [{ title: "Travel keyword architecture", copy: "Map destination, package, activity, itinerary, and question-led demand without cannibalisation.", items: ["Keyword clustering", "Destination hierarchy", "Package mapping", "Seasonal roadmap"] }, { title: "Technical and on-page SEO", copy: "Improve discovery, relevance, usability, and connections across a complex catalogue.", items: ["Indexing review", "Templates", "Internal links", "Structured content"] }, { title: "Enquiry-focused content", copy: "Balance genuine travel utility with differentiation, trust, and clear conversion routes.", items: ["Content briefs", "Itinerary structure", "Trust planning", "CTA improvement"] }],
    outcomes: ["Clear destination and package hierarchy", "Reduced keyword overlap", "Useful content connected to money pages", "Better mobile enquiry journeys"], process: sharedProcess,
    faqs: [{ question: "What is travel SEO?", answer: "Travel SEO improves organic discovery for destinations, tours, packages, experiences, and traveller questions through research, site structure, technical SEO, useful content, internal links, and conversion planning." }, { question: "Can SEO work for a small travel agency?", answer: "Yes, when priorities match the agency’s actual destinations, offers, authority, resources, and customer demand. Focused relevance can be more useful than trying to cover every destination." }, { question: "Do you write travel content?", answer: "GrowthLabs can plan search-led page structures and content briefs. Writing scope and subject-matter inputs are agreed per project so content stays accurate and genuinely useful." }],
    related: [{ label: "Hotel digital marketing", href: "/hotel-digital-marketing-agency" }, { label: "SEO expert in Nepal", href: "/seo-expert-in-nepal" }]
  },
  {
    slug: "social-media-marketing-packages", eyebrow: "Scope and pricing", title: "Social media marketing packages shaped around the work that creates value.", metaTitle: "Social Media Marketing Packages & Pricing | GrowthLabs", description: "Compare the strategy, creative, publishing, paid media, reporting, and conversion elements that shape social media marketing package pricing.",
    intro: "A responsible package starts with channel roles, content complexity, creative resources, paid media, approval workflow, community needs, and business goals. GrowthLabs scopes those variables before recommending a plan.", promise: "Know what you are paying for, why it is included, and how success will be evaluated.",
    challenges: [{ title: "A post count is not a strategy", copy: "Quantity says nothing about audience insight, creative quality, distribution, or the customer journey." }, { title: "Hidden production assumptions", copy: "Filming, design, copy, editing, approvals, and asset access materially change the workload." }, { title: "Paid media blurred with management", copy: "Ad spend, campaign management, creative testing, and organic publishing should be clearly separated." }],
    capabilities: [{ title: "Foundation", copy: "For brands that need positioning, channel direction, and a workable publishing system.", items: ["Audience and channel review", "Content pillars", "Monthly direction", "Measurement plan"] }, { title: "Growth", copy: "For consistent strategic content plus campaign and conversion support.", items: ["Creative briefs", "Publishing workflow", "Campaign planning", "Monthly insights"] }, { title: "Performance", copy: "For brands connecting organic social, paid media, testing, landing pages, and deeper measurement.", items: ["Paid social", "Performance creative", "Retargeting", "Conversion review"] }],
    outcomes: ["Scope matched to actual production", "Clear inclusions and responsibilities", "Separation of fees and ad spend", "A measurement plan beyond vanity metrics"], process: sharedProcess,
    faqs: [{ question: "How much does social media marketing cost in Nepal?", answer: "Pricing varies with channels, strategic depth, number and complexity of assets, filming or editing, paid-media management, community support, approval workflow, and reporting. GrowthLabs provides a custom scope after review." }, { question: "Is ad spend included?", answer: "Ad spend should normally be shown separately from strategy, creative, publishing, and campaign-management fees so the investment is transparent." }, { question: "Can I buy only strategy?", answer: "Yes. A focused strategy or audit can establish positioning, audiences, pillars, formats, campaign opportunities, measurement, and an execution roadmap for your internal team." }],
    related: [{ label: "Social media agency in Nepal", href: "/social-media-marketing-agency-in-nepal" }, { label: "Discuss your scope", href: "/contact" }]
  },
  {
    slug: "advertising-agency-in-nepal", eyebrow: "Paid growth / Nepal", title: "Advertising in Nepal connected to offers, landing pages, and measurable action.", metaTitle: "Advertising Agency in Nepal | GrowthLabs", description: "Performance advertising agency in Nepal for Google Ads, Meta Ads, TikTok Ads, retargeting, creative direction, landing pages, CRO, and conversion tracking.",
    intro: "GrowthLabs plans paid media as a connected system: demand, audience, offer, creative, campaign structure, landing experience, tracking, and the follow-up that turns interest into business.", promise: "Make media decisions with a clearer view of what creates qualified action—not just clicks.",
    challenges: [{ title: "Campaign-first thinking", copy: "Media cannot rescue a weak offer, unclear positioning, or a landing page that breaks the message." }, { title: "Creative fatigue", copy: "Performance requires a repeatable way to develop hypotheses, variants, and useful learning." }, { title: "Unreliable attribution", copy: "Decisions weaken when conversion events, forms, calls, pixels, analytics, and reporting disagree." }],
    capabilities: [{ title: "Google Ads", copy: "Capture existing intent with appropriate keywords, structure, message, negatives, and landing pages.", items: ["Search campaigns", "Keyword planning", "Ad copy", "Conversion tracking"] }, { title: "Meta and TikTok", copy: "Create and convert demand through audience strategy, performance creative, and sequenced journeys.", items: ["Prospecting", "Retargeting", "Lead generation", "Creative testing"] }, { title: "Conversion system", copy: "Align paid traffic with offers, pages, proof, tracking, and next-step handling.", items: ["Landing pages", "CRO review", "Analytics", "Reporting"] }],
    outcomes: ["Cleaner campaign-to-page alignment", "Transparent measurement priorities", "A structured creative learning loop", "Budget directed by business relevance"], process: sharedProcess,
    faqs: [{ question: "Which ad platforms do you manage?", answer: "GrowthLabs supports Google Ads, Meta Ads, and TikTok Ads, including campaign strategy, structure, audience and keyword planning, creative direction, retargeting, landing pages, and measurement." }, { question: "Do you guarantee leads or sales?", answer: "No responsible advertiser can guarantee results because the market, offer, price, sales process, competition, budget, and customer behaviour also matter. GrowthLabs focuses on disciplined execution and improvement." }, { question: "Is creative included?", answer: "Creative direction and requirements can be included. Design, filming, editing, talent, or production scope is defined separately so responsibilities and costs are clear." }],
    related: [{ label: "Social media marketing", href: "/social-media-marketing-agency-in-nepal" }, { label: "Digital marketing agency in Nepal", href: "/digital-marketing-agency-in-nepal" }]
  },
  {
    slug: "digital-marketing-agency-in-kathmandu", eyebrow: "GrowthLabs / Kathmandu", title: "Digital marketing agency in Kathmandu for connected, measurable growth.", metaTitle: "Digital Marketing Agency in Kathmandu | GrowthLabs", description: "Founder-led digital marketing agency in Kathmandu for SEO, paid ads, social media, websites, local search, content, CRO, analytics, and growth strategy.",
    intro: "GrowthLabs supports businesses in Kathmandu Valley with direct founder access and a practical system spanning visibility, paid demand, website journeys, local search, tracking, and conversion.", promise: "Combine local market context with disciplined full-funnel execution.",
    challenges: [{ title: "Local visibility is fragmented", copy: "Search results, Maps, reviews, social profiles, directories, and the website shape one combined impression." }, { title: "Every channel has a different message", copy: "Customers lose confidence when ads, profiles, pages, offers, and follow-up do not agree." }, { title: "Reports stop at traffic", copy: "The useful question is what visitors did, where intent weakened, and what should change next." }],
    capabilities: [{ title: "Local demand", copy: "Map Kathmandu and Nepal-wide search intent to appropriate service, industry, and location pages.", items: ["Local SEO", "Google Business Profile", "Reviews", "Location strategy"] }, { title: "Acquisition", copy: "Use search, paid social, content, and campaigns according to the customer journey.", items: ["SEO", "Google Ads", "Meta and TikTok", "Content strategy"] }, { title: "Conversion", copy: "Strengthen the website, offer, trust, calls to action, tracking, and learning loop.", items: ["Landing pages", "CRO", "Analytics", "Reporting"] }],
    outcomes: ["Stronger Kathmandu relevance", "Consistent messages across channels", "Clearer local enquiry journeys", "Direct access to founder-led strategy"], process: sharedProcess,
    faqs: [{ question: "Does GrowthLabs work with businesses in Kathmandu?", answer: "Yes. GrowthLabs is based in Nepal and serves businesses in Kathmandu Valley and across Nepal, as well as selected international projects." }, { question: "What digital marketing services do you provide?", answer: "Services include digital strategy, SEO, Google Ads, Meta and TikTok ads, social media, website and landing-page strategy, content, local SEO, CRO, analytics, and tracking." }, { question: "Should I choose the Kathmandu or Nepal service page?", answer: "This page explains local Kathmandu relevance. The Nepal agency page presents the broader full-service offer. You do not need to submit separate enquiries." }],
    related: [{ label: "Digital marketing agency in Nepal", href: "/digital-marketing-agency-in-nepal" }, { label: "SEO company in Nepal", href: "/seo-company-in-nepal" }]
  }
];

export const commercialLandingBySlug = Object.fromEntries(commercialLandings.map((page) => [page.slug, page])) as Record<string, CommercialLanding>;
