import Image from "next/image";
import Link from "next/link";
import { Arrow } from "./icons";
import { ContactCta, PageIntro, SectionHeading } from "./ui";
import { seoCapabilities, seoIndustries, seoProblems, seoProcess, type SeoFaq } from "@/content/seo";
import { siteConfig } from "@/content/site";

type Props = { variant: "expert" | "company"; faqs: SeoFaq[] };

export function SeoLanding({ variant, faqs }: Props) {
  const expert = variant === "expert";
  const title = expert ? "SEO expert in Nepal for visibility that supports real growth." : "SEO company in Nepal built for rankings, leads, and long-term growth.";
  const intro = expert ? "Work directly with Rohan Neure on the parts of SEO that determine whether visibility becomes business: search intent, technical foundations, page architecture, useful content, internal links, local relevance, and conversion paths." : "GrowthLabs builds complete SEO systems through keyword strategy, technical SEO, content planning, local search, on-page work, internal linking, and conversion-focused execution.";
  const comparisons = expert ? [["Random keyword targeting", "Keyword clustering and page mapping"], ["Blogs without business intent", "Content built around search intent and conversion"], ["Technical fixes only", "Technical SEO, content, links, and CRO together"], ["Ranking reports only", "Rankings, traffic quality, leads, and next actions"]] : [["Focus only on rankings", "Rankings, traffic quality, and conversion"], ["Random keywords", "Clustering, intent, and page mapping"], ["Blogs without strategy", "Content connected to commercial pages"], ["Generic reporting", "Insight-led next-step recommendations"]];
  const schemas = [{ "@context": "https://schema.org", "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: "Home", item: siteConfig.domain }, { "@type": "ListItem", position: 2, name: "Services", item: `${siteConfig.domain}/services` }, { "@type": "ListItem", position: 3, name: expert ? "SEO Expert in Nepal" : "SEO Company in Nepal", item: `${siteConfig.domain}/${expert ? "seo-expert-in-nepal" : "seo-company-in-nepal"}` }] }, { "@context": "https://schema.org", "@type": "Service", name: "SEO Services in Nepal", serviceType: "Search engine optimization", areaServed: { "@type": "Country", name: "Nepal" }, provider: { "@type": "ProfessionalService", name: siteConfig.brandName, url: siteConfig.domain, founder: { "@type": "Person", name: siteConfig.fullName } } }];
  return <>
    <PageIntro eyebrow={expert ? "Rohan Neure · Founder-led SEO strategy" : "GrowthLabs / SEO"} title={title}><p>{intro}</p>{expert && <p className="mt-4">The objective is not rankings in isolation. It is to help the right people discover the business, understand why it fits, and take a measurable next step.</p>}<div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link className="button button-primary" href="/contact">{expert ? "Request an SEO review" : "Request an SEO audit"} <Arrow /></Link><a className="button" href="#seo-services">Explore the SEO approach <Arrow /></a></div>{expert && <p className="mt-4 text-sm">Share your website, target market, and most important SEO challenge. The first conversation identifies the constraint before scope is recommended.</p>}</PageIntro>
    {expert && <section className="shell pb-16"><div className="grid items-center gap-8 border-t border-[var(--line)] pt-8 md:grid-cols-[1fr_2fr]"><Image className="aspect-square w-full max-w-sm object-cover" src={siteConfig.profileImage} alt="Rohan Neure, SEO expert and founder of GrowthLabs" width={1254} height={1254} sizes="(max-width: 768px) 100vw, 33vw" priority /><div><p className="eyebrow">Founder-led SEO</p><h2 className="section-title mt-5">Strategy without the layers.</h2><p className="lede mt-6">Work directly with Rohan on the keyword map, technical priorities, page structure, content direction, local visibility, and conversion path.</p></div></div></section>}
    <section className="section"><div className="shell"><SectionHeading eyebrow="Why SEO struggles" title="SEO is a system. Weak links compound." copy="Publishing more is not the same as building search visibility. Strong SEO needs the right demand, pages, technical foundation, content, links, and conversion journey." /><div className="mt-14 grid gap-8 md:grid-cols-2 lg:grid-cols-3">{seoProblems.map((item) => <article className="card" key={item.title}><h3 className="font-serif text-2xl">{item.title}</h3><p className="mt-3 text-sm leading-6 text-[var(--muted)]">{item.copy}</p></article>)}</div></div></section>
    <section id="seo-services" className="section scroll-mt-24 bg-[linear-gradient(135deg,#21170d,#4a2005)] text-[var(--paper)]"><div className="shell"><SectionHeading eyebrow="SEO services with direct specialist involvement" title="Scope follows the constraint." copy="The plan is shaped by search intent, opportunity, website condition, competition, content quality, local visibility, and business goals." /><div className="mt-16 grid gap-10 md:grid-cols-2">{seoCapabilities.map((item, index) => <article className="border-t border-white/30 pt-5" key={item.title}><p className="eyebrow !text-[var(--sun)]">0{index + 1}</p><h3 className="mt-5 font-serif text-3xl">{item.title}</h3><p className="mt-4 leading-7 text-white/65">{item.summary}</p><ul className="mt-5 grid gap-2 sm:grid-cols-2">{item.items.map((capability) => <li className="border-t border-white/15 py-2 text-sm text-white/75" key={capability}>{capability}</li>)}</ul></article>)}</div>{expert && <Link className="button mt-12 border-white text-white hover:bg-white hover:text-[var(--ink)]" href="/contact">Request an SEO review <Arrow /></Link>}</div></section>
    <section className="section"><div className="shell"><SectionHeading eyebrow="The model" title={expert ? "Direct expert strategy. Structured execution when you need it." : "Founder-led strategy with a company-level SEO system."} copy={expert ? "Choose direct specialist input for an audit, roadmap, technical direction, or page plan. Continue with GrowthLabs when you need implementation and ongoing improvement." : "GrowthLabs combines direct strategic access to Rohan Neure with the planning, implementation, tracking, and iteration expected from an SEO company."} /><div className="mt-12 md:ml-[25%]"><div className="grid gap-4 sm:grid-cols-2"><Link className="button button-primary" href="/seo-expert-in-nepal">SEO expert in Nepal <Arrow /></Link><Link className="button" href="/seo-company-in-nepal">SEO company in Nepal <Arrow /></Link></div></div></div></section>
    <section className="section"><div className="shell"><SectionHeading eyebrow="Process" title="From research to execution to improvement." /><ol className="mt-14 md:ml-[25%]">{seoProcess.map((step, index) => <li className="grid gap-3 border-t border-[var(--line)] py-6 sm:grid-cols-[4rem_1fr_2fr]" key={step.title}><span className="eyebrow">0{index + 1}</span><h3 className="font-serif text-2xl">{step.title}</h3><p className="leading-7 text-[var(--muted)]">{step.copy}</p></li>)}</ol></div></section>
    <section className="section"><div className="shell"><SectionHeading eyebrow="Built for" title="SEO shaped around the business model." /><div className="mt-14 grid gap-6 sm:grid-cols-2 lg:grid-cols-3">{seoIndustries.map((industry) => <p className="card font-serif text-2xl" key={industry}>{industry}</p>)}</div></div></section>
    <section className="section"><div className="shell"><SectionHeading eyebrow="A better comparison" title={expert ? "Typical SEO provider vs GrowthLabs SEO." : "Typical SEO company vs GrowthLabs."} /><div className="mt-14 overflow-x-auto md:ml-[25%]"><table className="w-full min-w-[38rem] border-collapse text-left"><thead><tr><th className="border-b border-[var(--ink)] p-4">Typical approach</th><th className="border-b border-[var(--ink)] p-4 text-[var(--accent)]">GrowthLabs approach</th></tr></thead><tbody>{comparisons.map(([a, b]) => <tr key={a}><td className="border-b border-[var(--line)] p-4 text-[var(--muted)]">{a}</td><td className="border-b border-[var(--line)] p-4 font-semibold">{b}</td></tr>)}</tbody></table></div></div></section>
    {expert && <section className="section"><div className="shell"><SectionHeading eyebrow="Advice your team can act on" title="A useful SEO review should tell you what to do next." copy="Scope determines the deliverables, but the final output should make priorities visible and implementation practical." /><ul className="mt-12 grid md:ml-[25%] md:grid-cols-2">{["Executive explanation of the most important constraints", "Prioritised roadmap based on likely value, effort, and dependency", "Evidence tied to queries, pages, templates, or technical behaviour", "Content, development, local-search, and conversion recommendations", "Ownership and sequencing from advice to implementation", "Measurement requirements and a baseline for review", "A decision on what should not be prioritised yet"].map((item) => <li className="border-t border-[var(--line)] py-4 pr-6" key={item}>{item}</li>)}</ul></div></section>}
    {expert && <section className="section"><div className="shell"><SectionHeading eyebrow="Reduce the risk" title="What to ask before hiring an SEO expert in Nepal." copy="Look for reasoning you can inspect—not a promise you cannot verify." /><div className="mt-14 grid gap-10 md:ml-[25%] md:grid-cols-2"><article><h3 className="font-serif text-3xl">Ask this</h3><ul className="mt-5">{["Which queries and pages are commercially important—and why?", "How will keywords be mapped to avoid cannibalisation?", "Which technical issues genuinely limit performance?", "What is included and who owns implementation?", "How will visibility connect to qualified action?", "What evidence supports the recommendation?"].map((item) => <li className="border-t border-[var(--line)] py-3" key={item}>{item}</li>)}</ul></article><article><h3 className="font-serif text-3xl">Treat this as a warning</h3><ul className="mt-5">{["Guaranteed first positions", "Secret methods", "Bulk link promises", "Generic reports without decisions", "Fabricated traffic or case studies", "Pricing disconnected from deliverables"].map((item) => <li className="border-t border-[var(--line)] py-3" key={item}>{item}</li>)}</ul></article></div></div></section>}
    <section className="section"><div className="shell"><SectionHeading eyebrow="Responsible expectations" title="The work should reflect the site—not a keyword quota." copy="Focused corrections can create fast learning, while competitive commercial growth usually requires sustained technical, content, internal-link, local, and authority work. Scope depends on website size, competition, markets, technical condition, content needs, implementation responsibility, and reporting depth." /><div className="mt-10 md:ml-[25%]"><Link className="button button-primary" href="/contact">{expert ? "Request an SEO review" : "Request a practical SEO plan"} <Arrow /></Link></div></div></section>
    <section className="section"><div className="shell"><SectionHeading eyebrow="FAQ" title="SEO in Nepal, answered." /><div className="mt-14 md:ml-[25%]">{faqs.map((item) => <details className="group border-t border-[var(--line)] py-5" key={item.question}><summary className="flex cursor-pointer list-none items-center justify-between gap-6 font-serif text-xl"><span>{item.question}</span><span aria-hidden="true" className="text-[var(--accent)] group-open:rotate-45">+</span></summary><p className="prose-copy mt-4 pr-8">{item.answer}</p></details>)}</div></div></section>
    <ContactCta />
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schemas).replace(/</g, "\\u003c") }} />
  </>;
}
