import Link from "next/link";
import { Arrow } from "@/components/icons";
import { PageIntro, SectionHeading } from "@/components/ui";
import { PerformanceEvidence } from "@/components/search-evidence";
import { services, siteConfig, tools } from "@/content/site";
import { pageMetadata } from "@/lib/metadata";
import { PageStructuredData } from "@/components/structured-data";
import { agencyAssets } from "@/content/agency-assets";

export const metadata = pageMetadata("GrowthLabs Services | SEO, Google Ads, Meta Ads & CRO", "Explore GrowthLabs services across SEO, Google Ads, Meta Ads, social media, websites, local SEO, CRO, analytics and tracking.", "/services");

const selector = [
  { symptom: "We are difficult to find on Google.", path: "SEO audit, keyword research, technical and on-page SEO, local SEO and content planning.", href: "/seo-expert-in-nepal", label: "Work with an SEO expert in Nepal" },
  { symptom: "We are difficult to find in Google Maps.", path: "Google Business Profile, local intent, business information, reviews, local pages and conversion measurement.", href: "/local-seo-services-in-nepal", label: "Explore local SEO services" },
  { symptom: "Our advertisements spend money but produce weak leads.", path: "Offer review, campaign structure, targeting, creative direction, landing-page alignment and conversion tracking.", href: "/google-ads-agency-in-nepal", label: "Explore Google Ads services" },
  { symptom: "Our Meta campaigns generate attention but not qualified action.", path: "Campaign objective, audience logic, creative system, destination, tracking, follow-up and lead-quality feedback.", href: "/meta-ads-agency-in-nepal", label: "Explore Meta Ads services" },
  { symptom: "Our website looks fine but does not explain or sell the offer.", path: "Positioning, information architecture, conversion copy, trust, calls to action, mobile experience and measurement.", href: "/web-design-company-in-nepal", label: "Explore web design in Nepal" },
  { symptom: "Our social channels are active but disconnected from business.", path: "Audience strategy, content pillars, creative direction, organic and paid distribution, retargeting and conversion paths.", href: "/social-media-marketing-agency-in-nepal", label: "Explore social media marketing" },
  { symptom: "We get traffic, but too few people act.", path: "Conversion review, message clarity, page hierarchy, trust, form and CTA improvement, behaviour analysis and testing.", href: "/conversion-rate-optimization-services", label: "Explore CRO services" },
  { symptom: "We need an SEO diagnosis before another retainer.", path: "Crawl evidence, indexation, templates, content quality, internal links, authority signals, local visibility and a prioritised implementation roadmap.", href: "/seo-audit-services-in-nepal", label: "Explore SEO audit services" },
  { symptom: "We cannot tell what is working.", path: "Measurement planning, GA4, Tag Manager, platform events, Search Console and reporting logic." },
  { symptom: "The channels feel disconnected.", path: "Customer-journey mapping, channel priorities, ownership, measurement and an integrated roadmap." },
];

const links: Record<string, { href: string; label: string }[]> = {
  seo: [{ href: "/seo-expert-in-nepal", label: "Work directly with Rohan Neure" }, { href: "/seo-company-in-nepal", label: "Compare the SEO company model" }, { href: "/seo-audit-services-in-nepal", label: "Request an SEO audit" }, { href: "/local-seo-services-in-nepal", label: "Explore local SEO services" }],
  "paid-advertising": [{ href: "/google-ads-agency-in-nepal", label: "Explore Google Ads services" }, { href: "/meta-ads-agency-in-nepal", label: "Explore Meta Ads services" }, { href: "/advertising-agency-in-nepal", label: "Compare multi-platform advertising" }],
  "social-media": [{ href: "/social-media-marketing-agency-in-nepal", label: "Explore social media marketing" }, { href: "/social-media-marketing-packages", label: "Compare package scope" }],
  websites: [{ href: "/web-design-company-in-nepal", label: "Explore web design in Nepal" }],
  cro: [{ href: "/conversion-rate-optimization-services", label: "Explore CRO services" }],
};

const analytics = { title: "Analytics, Tracking & Performance Analysis", slug: "analytics", summary: "Define meaningful events, check whether platforms receive reliable signals, and turn reporting into decisions rather than dashboard decoration.", capabilities: ["Measurement planning", "GA4 and Tag Manager guidance", "Platform conversion events", "Search Console analysis", "Lead-source and landing-page review"], value: "Understand which pages, campaigns, queries and offers create movement—and where the journey breaks." };
const reporting = { title: "Reporting & Performance Analysis", slug: "reporting", summary: "Connect search, media, page and conversion evidence to the decisions the business needs to make next.", capabilities: ["Decision-led scorecards", "Search and campaign analysis", "Landing-page behaviour", "Lead-quality feedback", "Next-priority recommendations"], value: "Know what to continue, change, stop or test instead of receiving another decorative dashboard." };
const automation = { title: "Marketing Automation", slug: "automation", summary: "Plan practical, consent-aware workflows that reduce repetitive work and improve how relevant enquiries or customers are followed up.", capabilities: ["Workflow mapping", "Lead routing", "Follow-up logic", "Tool and ownership requirements", "Measurement checkpoints"], value: "Build a maintainable workflow around a real operational need—not automation for its own sake." };
const serviceList = [...services, analytics, reporting, automation];
const serviceIds: Record<string, string> = { strategy: "digital-marketing-strategy", content: "content-marketing" };
const paths = [
  ["Search growth", "SEO audit + keyword mapping + technical and on-page work + commercial content + CRO + measurement."],
  ["Lead generation", "Offer review + Google or Meta campaigns + landing page + tracking + lead-quality feedback."],
  ["Website growth", "Positioning + keyword-led architecture + conversion copy + UX planning + technical SEO + analytics."],
  ["Local demand", "Google Business Profile + local keyword mapping + service pages + reviews + call and enquiry tracking."],
  ["Connected growth", "Strategy + phased SEO, paid media, content, website and CRO work around one customer journey."],
];
const models = [
  ["Focused audit or strategy sprint", "For a diagnosis, second opinion, keyword architecture, campaign review, website plan or prioritised roadmap."],
  ["Project-based implementation", "For a defined outcome such as a landing-page system, SEO foundation, campaign launch or tracking rebuild."],
  ["Ongoing growth support", "For sustained implementation, measurement and iteration across one or several channels."],
  ["Specialist support for your team", "For internal staff or another provider who need research, direction, review or quality control."],
];
const process = ["Diagnose", "Research", "Prioritise", "Build", "Measure", "Improve"];
const specialistPages = [
  ["Digital marketing agency in Nepal", "/digital-marketing-agency-in-nepal", "The complete national agency model and connected service system."],
  ["Digital marketing agency in Kathmandu", "/digital-marketing-agency-in-kathmandu", "Local context for Kathmandu Valley businesses, from the real Bhaktapur base."],
  ["SEO company in Nepal", "/seo-company-in-nepal", "Ongoing organisation-led SEO across technical, content, local search and CRO."],
  ["SEO expert in Nepal", "/seo-expert-in-nepal", "Direct specialist SEO strategy, review and implementation guidance from Rohan."],
  ["Advertising agency in Nepal", "/advertising-agency-in-nepal", "Google, Meta and TikTok advertising connected to pages, tracking and follow-up."],
  ["Google Ads agency in Nepal", "/google-ads-agency-in-nepal", "Google Search and campaign management connected to landing pages, conversion actions and lead quality."],
  ["Meta Ads agency in Nepal", "/meta-ads-agency-in-nepal", "Facebook and Instagram advertising connected to creative, destination, measurement and lead quality."],
  ["Conversion rate optimisation services", "/conversion-rate-optimization-services", "Research-led improvement across offer clarity, UX, proof, calls to action, forms and measurement."],
  ["SEO audit services in Nepal", "/seo-audit-services-in-nepal", "Technical, on-page, content, local and measurement evidence translated into a prioritised roadmap."],
  ["Local SEO services in Nepal", "/local-seo-services-in-nepal", "Google Business Profile, Maps relevance, local pages, reviews and measurable contact journeys."],
  ["Social media agency in Nepal", "/social-media-marketing-agency-in-nepal", "Organic and paid social strategy connected to business action."],
  ["Social media package planning", "/social-media-marketing-packages", "Foundation, Growth and Performance scopes with transparent pricing logic."],
  ["Web design company in Nepal", "/web-design-company-in-nepal", "Marketing-site strategy, SEO architecture, content, CRO and agreed implementation."],
  ["Hotel digital marketing", "/hotel-digital-marketing-agency", "Search, campaigns and website journeys supporting qualified hotel demand."],
  ["SEO for travel agencies", "/seo-for-travel-agency", "Destination, package, itinerary and seasonal search architecture."],
];
const faqs = [
  ["Do I need every service listed on this page?", "No. The right scope is based on the constraint, evidence, budget, internal capacity and dependencies. A focused page or tracking fix may be more valuable than another channel."],
  ["Can GrowthLabs audit work completed by another provider?", "Yes. GrowthLabs can review SEO, campaigns, website structure, landing pages, tracking or the connected customer journey without requiring a complete rebuild."],
  ["Do you provide implementation as well as strategy?", "Yes. Engagements can include strategy only, a defined implementation project, ongoing support or specialist direction for your existing team."],
  ["Which advertising platforms do you support?", "GrowthLabs works with Google Ads, Meta Ads and TikTok Ads. The appropriate platform depends on demand, audience, creative requirements, offer, budget and website readiness."],
  ["Can you improve an existing website without redesigning everything?", "Yes. Many problems can be addressed through positioning, structure, content, trust, calls to action, internal links, technical fixes and focused landing pages."],
  ["Do you offer one-off projects?", "Yes. An audit, roadmap, keyword map, landing page, tracking plan or focused optimisation project can be scoped around a clear objective and deliverable."],
  ["How is the right starting service chosen?", "GrowthLabs reviews the business goal, current performance, website, data and operational constraints, then recommends the highest-value solvable constraint."],
  ["How do I request a proposal?", "Share your website, offer, target market, current marketing, primary challenge, desired outcome and any important deadline."],
];

export default function ServicesPage() {
  return <>
    <PageIntro breadcrumbs={[{ label: "Services" }]} eyebrow="SEO · Google Ads · Meta Ads · Websites · CRO" title="Digital marketing services connected around growth." visual={agencyAssets.brandStrategy}><p>GrowthLabs brings SEO, Google Ads, Meta Ads, social media, content, websites, local visibility, analytics and conversion together around the business problem—not around a prebuilt bundle.</p><p className="mt-4">Start with the constraint. Build the capabilities that solve it. Measure whether the complete journey improves.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link className="button button-primary" href={siteConfig.cta.primary.href} data-cta-intent="growth-review" data-cta-location="services-hero" data-cta-channel="contact">{siteConfig.cta.primary.headerLabel} <Arrow /></Link><a className="button" href="#choose">Choose by your challenge <Arrow /></a></div><p className="mt-4 font-mono text-[.68rem] uppercase leading-5 tracking-[.04em]">{siteConfig.cta.reassurance} Share the result you want and what is getting in the way.</p></PageIntro>
    <div className="signal-band"><ul className="shell grid py-1 font-mono text-[.68rem] font-bold uppercase tracking-[.055em] sm:grid-cols-2 lg:grid-cols-4">{["Founder-led strategy", "Focused or connected scopes", "Search + acquisition + conversion", "Clear deliverables"].map((item, index) => <li className="flex items-center gap-3 border-black/25 py-4 sm:border-r sm:px-4 sm:first:pl-0 sm:last:border-0" key={item}><span>0{index + 1}</span>{item}</li>)}</ul></div>
    <PerformanceEvidence compact searchIds={["dubai-water-adventure"]} paidIds={["saas-google-ads"]} title="Evidence across organic search and paid acquisition." copy="The same research discipline changes shape by channel and market. These source captures show organic visibility for a tourism website and account-reported Google Ads activity for a SaaS business; each engagement still requires its own baseline, scope, conversion definitions and commercial context." />
    <section className="section" id="choose"><div className="shell"><SectionHeading eyebrow="Start with the symptom" title="You may not need more marketing. You may need the right intervention." /><div className="mt-14 grid gap-8 md:ml-[25%] md:grid-cols-2">{selector.map((item) => <article className="card" key={item.symptom}><h3 className="font-serif text-2xl">“{item.symptom}”</h3><p className="mt-4 leading-7 text-[var(--muted)]">{item.path}</p>{item.href && <Link className="text-link mt-5" href={item.href}>{item.label} <Arrow /></Link>}</article>)}</div><div className="mt-10 md:ml-[25%]"><Link className="button button-primary" href="/contact">Discuss the right starting point <Arrow /></Link></div></div></section>
    <section className="section section-dark"><div className="shell"><SectionHeading eyebrow="Complete service catalogue" title="Direction before activity. Value before volume." /><div className="mt-16">{serviceList.map((service, index) => <article id={serviceIds[service.slug] ?? service.slug} className="scroll-mt-28 grid gap-7 border-t border-white/30 py-7 lg:grid-cols-[.35fr_1fr_1fr]" key={service.slug}><div><p className="eyebrow !text-[var(--sun)]">0{index + 1}</p><h3 className="mt-5 font-serif text-3xl leading-none tracking-[-.045em]">{service.title}</h3></div><p className="leading-7 text-white/70">{service.summary}</p><div><p className="eyebrow !text-white/45">Capabilities</p><ul className="mt-3">{service.capabilities.map((item) => <li className="border-t border-white/15 py-2 font-mono text-[.68rem] uppercase tracking-[.03em] text-white/65" key={item}>{item}</li>)}</ul><p className="mt-5 text-sm leading-6 text-white/60"><strong className="text-white">Expected value:</strong> {service.value}</p><div className="mt-5 flex flex-wrap gap-4">{links[service.slug]?.map((link) => <Link className="border-b border-white/40 pb-1 text-sm font-semibold hover:text-[var(--sun)]" href={link.href} key={link.href}>{link.label} <Arrow /></Link>)}</div></div></article>)}</div><Link className="button mt-12 border-white text-white hover:bg-[var(--sun)] hover:text-[var(--ink)]" href={siteConfig.cta.primary.href} data-cta-intent="growth-review" data-cta-location="services-catalogue" data-cta-channel="contact">{siteConfig.cta.primary.headerLabel} <Arrow /></Link></div></section>
    <section className="section"><div className="shell"><SectionHeading eyebrow="Specialist and industry pages" title="Continue with the page closest to your decision." copy="Each page owns a distinct search and buying intent, so you can compare the relevant scope without forcing unrelated services together." /><div className="mt-14 grid gap-6 md:ml-[25%] md:grid-cols-2">{specialistPages.map(([title, href, copy]) => <article className="card" key={href}><h3 className="font-serif text-2xl"><Link className="hover:text-[var(--accent)]" href={href}>{title}</Link></h3><p className="mt-3 leading-7 text-[var(--muted)]">{copy}</p><Link className="text-link mt-5" href={href}>Explore this page <Arrow /></Link></article>)}</div></div></section>
    <section className="section"><div className="shell"><SectionHeading eyebrow="One system, different starting points" title="The strongest scope is the smallest one that solves the real problem." /><div className="mt-14 grid gap-8 md:ml-[25%] md:grid-cols-2">{paths.map(([title, copy]) => <article className="card" key={title}><h3 className="font-serif text-2xl">{title}</h3><p className="mt-3 leading-7 text-[var(--muted)]">{copy}</p></article>)}</div></div></section>
    <section className="section"><div className="shell"><SectionHeading eyebrow="Scope follows the problem" title="Work with GrowthLabs in the way the challenge requires." /><div className="mt-14 grid gap-8 md:ml-[25%] md:grid-cols-2">{models.map(([title, copy]) => <article className="card" key={title}><h3 className="font-serif text-2xl">{title}</h3><p className="mt-3 leading-7 text-[var(--muted)]">{copy}</p></article>)}</div><div className="mt-10 md:ml-[25%]"><Link className="button button-primary" href="/contact">Discuss an engagement <Arrow /></Link></div></div></section>
    <section className="section"><div className="shell"><SectionHeading eyebrow="Digital marketing process" title="Clear priorities and visible reasoning." /><ol className="mt-14 grid gap-6 md:ml-[25%] sm:grid-cols-2 lg:grid-cols-3">{process.map((step, index) => <li className="card" key={step}><p className="eyebrow">0{index + 1}</p><h3 className="mt-4 font-serif text-2xl">{step}</h3><p className="mt-3 text-sm leading-6 text-[var(--muted)]">{["Review the business, audience, offer, website, data and constraints.", "Study demand, competitors, campaigns, behaviour and the conversion journey.", "Rank opportunities by value, evidence, effort, dependency and speed to learning.", "Implement the agreed pages, campaigns, content, tracking, local or CRO work.", "Evaluate meaningful indicators without pretending attribution is perfect.", "Use evidence to continue, change, stop or test—and define the next priority."][index]}</p></li>)}</ol></div></section>
    <section className="section bg-[var(--surface)]"><div className="shell"><SectionHeading eyebrow="Practical resources" title="Guides for the decisions behind the services." copy="Use a source-backed definition, comparison, checklist or template before deciding whether you need strategy, implementation or ongoing support." /><div className="mt-12 grid border-b border-[var(--line-strong)] md:ml-[25%] sm:grid-cols-2">{[["What is SEO?", "/insights/what-is-seo"], ["Digital marketing process", "/insights/digital-marketing-process"], ["Facebook lead generation ads", "/insights/facebook-lead-generation-ads"], ["Website development checklist", "/insights/website-development-checklist"]].map(([label, href]) => <Link className="flex min-h-20 items-center justify-between border-t border-[var(--line-strong)] py-4 pr-5 font-bold hover:bg-[var(--sun)] sm:odd:border-r sm:odd:pl-4" href={href} key={href}>{label} <Arrow /></Link>)}</div><div className="mt-8 md:ml-[25%]"><Link className="text-link" href="/insights">Explore all GrowthLabs insights <Arrow /></Link></div></div></section>
    <section className="section"><div className="shell"><SectionHeading eyebrow="Working stack" title="Tools support decisions. They do not replace judgement." /><ul className="mt-10 grid border-b border-[var(--line-strong)] md:ml-[25%] sm:grid-cols-2 lg:grid-cols-4">{tools.map((tool, index) => <li className="flex min-h-14 items-center gap-3 border-t border-[var(--line-strong)] px-3 font-mono text-[.68rem] font-bold uppercase tracking-[.04em] sm:border-r" key={tool}><span className="text-[var(--accent)]">{String(index + 1).padStart(2, "0")}</span>{tool}</li>)}</ul></div></section>
    <section className="section"><div className="shell"><SectionHeading eyebrow="Scope, fit and engagement" title="Frequently asked questions." /><div className="mt-14 md:ml-[25%]">{faqs.map(([question, answer]) => <details className="group border-t border-[var(--line)] py-5" key={question}><summary className="flex min-h-11 cursor-pointer list-none items-center justify-between gap-6 font-serif text-xl"><span>{question}</span><span aria-hidden="true" className="text-[var(--accent)] group-open:rotate-45">+</span></summary><p className="prose-copy mt-4 pr-8">{answer}</p></details>)}</div></div></section>
    <section className="section signal-grid"><div className="shell grid gap-8 md:grid-cols-[1fr_3fr]"><p className="eyebrow">Choose the next priority</p><div><h2 className="section-title">Tell GrowthLabs what is not working. Build the right next step.</h2><p className="mt-6 max-w-2xl text-lg leading-8 text-black/65">{siteConfig.cta.microcopy}</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link className="button button-primary" href={siteConfig.cta.primary.href} data-cta-intent="growth-review" data-cta-location="services-final" data-cta-channel="contact">{siteConfig.cta.primary.headerLabel} <Arrow /></Link><a className="button" href={siteConfig.cta.whatsapp.href} target="_blank" rel="noopener noreferrer" data-cta-intent="growth-review" data-cta-location="services-final" data-cta-channel="whatsapp">{siteConfig.cta.whatsapp.label} <Arrow direction="up-right" /></a></div><p className="mt-5 font-mono text-[.72rem] uppercase leading-5 tracking-[.04em] text-black/65">{siteConfig.cta.reassurance}</p></div></div></section>
    <PageStructuredData path="/services" faqs={faqs.map(([question, answer]) => ({ question, answer }))} />
  </>;
}
