import Image from "next/image";
import Link from "next/link";
import { Arrow } from "@/components/icons";
import { PageStructuredData } from "@/components/structured-data";
import { PerformanceEvidence } from "@/components/search-evidence";
import { CredentialProof } from "@/components/credential-proof";
import { PageIntro, SectionHeading } from "@/components/ui";
import { industries, process, services, siteConfig } from "@/content/site";
import { pageMetadata } from "@/lib/metadata";
import { agencyAssets } from "@/content/agency-assets";

export const metadata = pageMetadata("Marketing Company in Nepal | GrowthLabs Digital Agency", "GrowthLabs is a founder-led marketing company and digital marketing agency in Nepal connecting SEO, Google Ads, Meta Ads, websites, tracking and CRO.", "/digital-marketing-agency-in-nepal");

const outcomes = [["Stronger visibility", "Build relevant organic, local, social and paid visibility around problems and services the business can genuinely solve."], ["Better-qualified traffic", "Prioritise search intent, audiences and messages that are more likely to create meaningful action."], ["Clearer conversion paths", "Give visitors the information, evidence and next step they need on desktop and mobile."], ["More useful measurement", "Connect campaigns and landing pages to qualified enquiries, bookings or sales where available systems permit."]];
const leaks = [["A website without search or conversion planning", "Thin service pages, generic claims, weak local relevance and unclear calls to action make every campaign work harder."], ["SEO without a keyword-to-page map", "Broad targeting causes missing pages, competing URLs, repetitive content and traffic without a relevant destination."], ["Paid media without message continuity", "Budget cannot compensate for an offer, advertisement and landing page that promise different things."], ["Social media without a role", "Content may create reach but little memory, trust or action when disconnected from the position and offer."], ["Data without a decision framework", "Impressions, clicks and sessions are context. Reporting must explain qualified movement and the next decision."]];
const reasons = [["Search intent before content volume", "Research identifies what people are trying to find and decide before pages or articles are commissioned."], ["SEO and CRO planned together", "Rankings create opportunity; clear positioning, useful evidence and an easy next step help capture it."], ["Paid media connected after the click", "Audience, creative, offer, landing page and tracking are treated as one performance path."], ["Recommendations follow the constraint", "GrowthLabs does not prescribe every channel when one focused fix can create more value."], ["Reporting leads to a decision", "The goal is to understand what to continue, change, stop or test—not to fill a dashboard."]];
const servicePresentation: Record<string, { id: string; title?: string; summary?: string; links?: { label: string; href: string }[] }> = {
  strategy: { id: "digital-marketing-strategy" },
  seo: { id: "seo", links: [{ label: "Work with an SEO expert in Nepal", href: "/seo-expert-in-nepal" }, { label: "Compare the SEO company model", href: "/seo-company-in-nepal" }] },
  "paid-advertising": { id: "paid-advertising", links: [{ label: "Explore performance advertising", href: "/advertising-agency-in-nepal" }, { label: "Explore Google Ads services", href: "/google-ads-agency-in-nepal" }] },
  "social-media": { id: "social-media", links: [{ label: "Explore social media marketing", href: "/social-media-marketing-agency-in-nepal" }] },
  websites: { id: "websites", links: [{ label: "Explore web design in Nepal", href: "/web-design-company-in-nepal" }] },
  content: { id: "content" },
  "local-seo": { id: "local-seo", links: [{ label: "Explore local SEO services", href: "/local-seo-services-in-nepal" }] },
  cro: {
    id: "analytics",
    title: "Analytics, tracking and CRO",
    summary: "Define meaningful events, improve data quality and remove friction from the pages and contact journeys that influence conversion.",
    links: [{ label: "Review analytics and CRO services", href: "/services#analytics" }],
  },
};
const checklist = [
  ["Can the agency explain the business problem first?", "A useful proposal starts with the audience, offer, customer journey, website and bottleneck—not standard deliverables."],
  ["Does the work match real demand and intent?", "Volume, reach and clicks have limited value when they do not connect to a relevant offer or decision."],
  ["Who will do the strategic work?", "Know whether the person who diagnoses the problem remains involved after the sale."],
  ["How will conversion and lead quality be measured?", "Ask which actions are tracked, where attribution is limited and how sales feedback informs optimisation."],
  ["Can the agency show proof with context?", "Credible evidence includes the starting point, period, scope, action and result—not an isolated percentage."],
  ["How will the website support campaigns?", "Strong targeting cannot fix an unclear offer, slow page, weak evidence or difficult enquiry process."],
  ["What is included, excluded and dependent on your team?", "Content, creative, development, approvals, spend and follow-up need clear ownership."],
  ["What happens after the first report?", "Data should become priorities, tests and decisions—not only monthly commentary."],
];
const faqs = [
  ["What does a marketing company in Nepal do?", "A capable marketing company or digital marketing agency can research the audience, plan strategy, improve SEO and local visibility, manage paid campaigns, develop social and content systems, strengthen websites, implement tracking and improve conversion. The useful mix depends on the business problem."],
  ["What digital marketing services does GrowthLabs provide?", "GrowthLabs provides strategy, SEO, local SEO, Google Business Profile support, Google Ads, Meta Ads, TikTok Ads, social media marketing, website and landing-page strategy, content, analytics, tracking and CRO."],
  ["How do I choose the best digital marketing company in Nepal?", "Compare its ability to diagnose the problem, explain channel roles, show contextual evidence, define ownership and deliverables, measure qualified outcomes and set realistic expectations. Choose for fit and reasoning—not the boldest claim."],
  ["How much do digital marketing services cost in Nepal?", "Cost depends on scope, competition, website condition, creative and content needs, advertising platforms, tracking complexity, implementation responsibility and pace. A responsible proposal explains work and exclusions before quoting."],
  ["Is GrowthLabs based in Kathmandu?", "GrowthLabs is based at Sallaghari Shopping Complex in Bhaktapur, within Kathmandu Valley. It serves clients across the Valley and throughout Nepal; it does not claim a Kathmandu city office."],
  ["Can SEO and paid advertising work together?", "Yes. Paid campaigns can provide faster learning while SEO builds compounding visibility. Shared keyword, offer, landing-page and conversion data can improve both."],
  ["How long does digital marketing take?", "Timing depends on channel, starting point, competition, budget, website, offer and implementation speed. Focused fixes may produce fast learning; organic growth and sustained acquisition normally require consistent work."],
  ["Will I work directly with Rohan Neure?", "Yes. Rohan leads the strategic review and remains involved in priorities, page and campaign direction, measurement and optimisation appropriate to the engagement."],
  ["Do you guarantee leads, sales or rankings?", "No responsible agency can guarantee those outcomes. GrowthLabs commits to transparent research, agreed execution, measurement and improvement."],
  ["How do we start?", "Share the website, offer, target market, current marketing and biggest growth challenge. The first review identifies whether the right next step is an audit, strategy, focused project or ongoing programme."],
];

export default function AgencyPage() {
  return <>
    <PageIntro breadcrumbs={[{ label: "Services", href: "/services" }, { label: "Digital Marketing Agency in Nepal" }]} eyebrow="SEO · Google Ads · Meta Ads · Founder-led in Nepal" title="Marketing company in Nepal for connected digital growth." visual={agencyAssets.growthSystem}><p><strong>GrowthLabs is a founder-led marketing company and digital marketing agency in Nepal.</strong> It connects SEO, Google Ads, Meta Ads, social media, content, websites, landing pages, local search, tracking and conversion rate optimisation into one practical growth system.</p><p className="mt-4">The goal is not more disconnected activity. It is a clearer journey from being discovered to being trusted—and from being trusted to becoming a qualified enquiry, booking or sale.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link className="button button-primary" href="/contact" data-cta-intent="digital-growth-review" data-cta-location="agency-hero" data-cta-channel="contact">Request a digital growth review <Arrow /></Link><Link className="button" href="/advertising-agency-in-nepal">Explore Google & Meta Ads <Arrow /></Link></div></PageIntro>
    <div className="border-y border-[var(--line)]"><ul className="shell grid py-1 text-sm font-semibold sm:grid-cols-2 lg:grid-cols-4">{["Based in Bhaktapur", "Direct founder involvement", "SEO + content systems", "Google Ads + Meta Ads + CRO"].map((item) => <li className="py-4" key={item}>{item}</li>)}</ul></div>
    <PerformanceEvidence compact searchIds={["australian-agency"]} paidIds={["london-home-services-ads"]} title="Cross-channel evidence, kept in its proper context." copy="One source capture shows monitored organic visibility for an agency; the other shows account-reported Google Ads activity for a home-services business. Together they demonstrate distinct measurement layers without pretending impressions, clicks or configured conversions prove revenue or sole attribution." />
    <CredentialProof ids={["googleAds", "metaAds", "semrush", "hubspot", "amazonAds", "googleReviews"]} title="A founder-led Nepal agency with supplied cross-platform credentials." copy="GrowthLabs presents its supplied platform-partner artwork alongside inspectable organic-search and paid-media account captures. The Google Reviews artwork displays a 5.0 rating without adding an unsupported review-count claim." />
    <section className="section"><div className="shell"><SectionHeading eyebrow="A connected agency model" title="Turn marketing activity into a customer journey." copy="Businesses often invest in posts, advertisements, blogs and website changes without creating consistent leads. GrowthLabs aligns the audience, offer, channel, message, page, conversion action and follow-up around the same commercial objective." /><div className="mt-14 grid gap-8 md:ml-[25%] md:grid-cols-2">{outcomes.map(([title, copy]) => <article className="card" key={title}><h3 className="font-serif text-2xl">{title}</h3><p className="mt-3 leading-7 text-[var(--muted)]">{copy}</p></article>)}</div></div></section>
    <section className="section"><div className="shell"><SectionHeading eyebrow="Where growth leaks" title="Effort is rarely the missing piece. Connection is." /><div className="mt-14 grid gap-8 md:grid-cols-2 lg:grid-cols-3">{leaks.map(([title, copy]) => <article className="card" key={title}><h3 className="font-serif text-2xl">{title}</h3><p className="mt-3 leading-7 text-[var(--muted)]">{copy}</p></article>)}</div></div></section>
    <section className="section section-dark"><div className="shell"><SectionHeading eyebrow="Digital marketing services in Nepal" title="Give every channel a clear job." /><div className="mt-16 border-b border-white/20">{services.map((service, index) => { const presentation = servicePresentation[service.slug]; return <article id={presentation.id} className="scroll-mt-28 grid gap-5 border-t border-white/25 py-7 md:grid-cols-[5rem_.8fr_1.2fr] md:items-start" key={service.slug}><p className="font-mono text-xs text-[var(--sun)]">0{index + 1}</p><h3 className="font-serif text-3xl leading-none tracking-[-.045em]">{presentation.title ?? service.title}</h3><div><p className="leading-7 text-white/65">{presentation.summary ?? service.summary}</p>{presentation.links && <div className="mt-5 flex flex-wrap gap-5">{presentation.links.map((link) => <Link className="border-b border-white/40 pb-1 text-sm font-semibold text-white hover:text-[var(--sun)]" href={link.href} key={link.href}>{link.label} <Arrow /></Link>)}</div>}</div></article>})}</div><div className="mt-12 flex flex-wrap items-center gap-5"><Link className="button border-white text-white hover:bg-[var(--sun)] hover:text-[var(--ink)]" href="/services">Explore all services <Arrow /></Link><Link className="text-link !text-[var(--sun)]" href="/digital-marketing-agency-in-kathmandu">See Kathmandu Valley service <Arrow /></Link></div></div></section>
    <section className="section"><div className="shell grid items-center gap-12 lg:grid-cols-[1fr_1fr]"><div><p className="eyebrow">Why GrowthLabs</p><h2 className="section-title mt-6">The person who understands the problem stays close to the work.</h2><p className="lede mt-6">Clients work directly with Rohan to understand the market, customer, offer, search opportunity, website, campaigns and conversion journey before scope is defined.</p><div className="mt-9">{reasons.map(([title, copy]) => <article className="border-t border-[var(--line)] py-4" key={title}><h3 className="font-serif text-xl">{title}</h3><p className="mt-2 text-sm leading-6 text-[var(--muted)]">{copy}</p></article>)}</div><Link className="text-link mt-6" href="/about">About GrowthLabs and Rohan Neure <Arrow /></Link></div><Image className="aspect-square w-full object-cover" src={siteConfig.profileImage} alt="Rohan Neure, founder of GrowthLabs in Bhaktapur, Nepal" width={1089} height={1089} sizes="(max-width: 1024px) 100vw, 45vw" /></div></section>
    <section className="section"><div className="shell"><SectionHeading eyebrow="Nepal context" title="Based in Bhaktapur. Serving Kathmandu Valley and businesses across Nepal." copy="Customers may discover a business through Search, Maps, Facebook, Instagram, TikTok, directories, referrals or messaging apps. GrowthLabs plans for that behaviour while applying disciplined foundations: clear positioning, useful content, accessible pages, responsible targeting and accurate measurement." /><div className="mt-12 grid gap-8 md:ml-[25%] md:grid-cols-2"><address className="card not-italic"><p className="eyebrow">GrowthLabs by Rohan Neure</p><p className="mt-4 font-serif text-2xl">{siteConfig.location}</p><a className="text-link mt-5" href={siteConfig.cta.phone.href}>{siteConfig.phoneDisplay}</a><br/><a className="text-link mt-3" href={siteConfig.cta.whatsapp.href} target="_blank" rel="noopener noreferrer">{siteConfig.cta.whatsapp.label} <Arrow direction="up-right" /></a><br/><a className="text-link mt-3" href={siteConfig.mapUrl} target="_blank" rel="noopener noreferrer">View Google Business Profile <Arrow direction="up-right" /></a><br/><Link className="text-link mt-3" href="/digital-marketing-agency-in-kathmandu">Explore Kathmandu Valley service <Arrow /></Link></address><ul>{["Nepal-wide keyword and competitor research", "Kathmandu Valley and service-area targeting", "Google Business Profile and local SEO", "Location-based advertising", "Review and trust planning", "Landing-page and follow-up improvement"].map((item) => <li className="border-t border-[var(--line)] py-3" key={item}>{item}</li>)}</ul></div></div></section>
    <section className="section"><div className="shell"><SectionHeading eyebrow="Industries" title="Strategy follows the way customers decide." /><div className="mt-14 grid gap-8 sm:grid-cols-2 lg:grid-cols-3">{industries.map((industry) => <article className="card" key={industry.title}><h3 className="font-serif text-2xl">{industry.title}</h3><p className="mt-3 text-sm leading-6 text-[var(--muted)]">{industry.copy}</p>{industry.title.startsWith("Hotels") && <Link className="text-link mt-5" href="/hotel-digital-marketing-agency">Hotel digital marketing <Arrow /></Link>}{industry.title.startsWith("Travel") && <Link className="text-link mt-5" href="/seo-for-travel-agency">SEO for travel agencies <Arrow /></Link>}</article>)}</div></div></section>
    <section className="section"><div className="shell"><SectionHeading eyebrow="A buyer's checklist" title="How to choose the best digital marketing agency in Nepal for your business." copy="“Best” should mean best fit—not the biggest claim." /><ol className="mt-14 md:ml-[25%]">{checklist.map(([question, answer], index) => <li className="grid gap-3 border-t border-[var(--line)] py-6 sm:grid-cols-[4rem_1fr_2fr]" key={question}><span className="eyebrow">0{index + 1}</span><h3 className="font-serif text-xl">{question}</h3><p className="leading-7 text-[var(--muted)]">{answer}</p></li>)}</ol><p className="mt-8 border-l-2 border-[var(--accent)] pl-5 md:ml-[25%]"><strong>Warning signs:</strong> guaranteed rankings or returns, secret methods, bulk low-quality links, fabricated reviews, or pricing that cannot be connected to deliverables.</p></div></section>
    <section className="section"><div className="shell"><SectionHeading eyebrow="From evidence to execution" title="Know what is happening, why it matters and what comes next." /><ol className="mt-14 md:ml-[25%]">{process.map((step, index) => <li className="grid gap-3 border-t border-[var(--line)] py-6 sm:grid-cols-[4rem_1fr_2fr]" key={step.title}><span className="eyebrow">0{index + 1}</span><h3 className="font-serif text-2xl">{step.title}</h3><p className="leading-7 text-[var(--muted)]">{step.copy}</p></li>)}</ol></div></section>
    <section className="section bg-[var(--surface)]"><div className="shell"><SectionHeading eyebrow="See the thinking" title="Use the process, comparison and planning guides." copy="The Insights library explains how GrowthLabs approaches channel selection and execution before a commercial scope is recommended." /><div className="mt-12 grid border-b border-[var(--line-strong)] md:ml-[25%] sm:grid-cols-2">{[["Digital marketing process", "/insights/digital-marketing-process"], ["SEO vs social media marketing", "/insights/seo-vs-social-media-marketing"], ["Social media content calendar", "/insights/social-media-content-calendar"], ["Website development checklist", "/insights/website-development-checklist"]].map(([label, href]) => <Link className="flex min-h-20 items-center justify-between border-t border-[var(--line-strong)] py-4 pr-5 font-bold hover:bg-[var(--sun)] sm:odd:border-r sm:odd:pl-4" href={href} key={href}>{label} <Arrow /></Link>)}</div></div></section>
    <section className="section"><div className="shell"><SectionHeading eyebrow="Scope, pricing and timelines" title="A proposal should explain what drives the investment." copy="GrowthLabs can scope a focused audit or strategy sprint, defined implementation, ongoing channel management or connected programme. Investment depends on markets, website condition, competition, content and creative needs, platforms, tracking complexity, responsibility and pace. Advertising spend and third-party costs are shown separately where applicable." /><div className="mt-10 max-w-3xl md:ml-[25%]"><p className="prose-copy">Focused corrections and paid-campaign learning can create useful signals relatively quickly. Competitive organic growth, stronger market positioning and reliable multi-channel acquisition normally require sustained work. Timing is discussed only after the starting point, dependencies and implementation capacity are understood.</p><Link className="button button-primary mt-8" href="/contact">Request a scoped recommendation <Arrow /></Link></div></div></section>
    <section className="section"><div className="shell"><SectionHeading eyebrow="Before choosing an agency" title="Frequently asked questions." /><div className="mt-14 md:ml-[25%]">{faqs.map(([question, answer]) => <details className="group border-t border-[var(--line)] py-5" key={question}><summary className="flex min-h-11 cursor-pointer list-none items-center justify-between gap-6 font-serif text-xl"><span>{question}</span><span aria-hidden="true" className="text-[var(--accent)] group-open:rotate-45">+</span></summary><p className="prose-copy mt-4 pr-8">{answer}</p></details>)}</div></div></section>
    <section className="section signal-grid"><div className="shell grid gap-8 md:grid-cols-[1fr_3fr]"><p className="eyebrow">Founder-led digital growth in Nepal</p><div><h2 className="section-title">Looking for an agency that connects strategy to execution?</h2><p className="mt-6 max-w-2xl text-lg leading-8 text-black/65">{siteConfig.cta.microcopy}</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link className="button button-primary" href="/contact" data-cta-intent="digital-growth-review" data-cta-location="agency-final" data-cta-channel="contact">Request a digital growth review <Arrow /></Link><a className="button" href={siteConfig.cta.whatsapp.href} target="_blank" rel="noopener noreferrer" data-cta-intent="digital-growth-review" data-cta-location="agency-final" data-cta-channel="whatsapp">{siteConfig.cta.whatsapp.label} <Arrow direction="up-right" /></a></div><p className="mt-5 font-mono text-[.72rem] uppercase leading-5 tracking-[.04em] text-black/65">{siteConfig.cta.reassurance} · {siteConfig.phoneDisplay}</p></div></div></section>
    <PageStructuredData path="/digital-marketing-agency-in-nepal" faqs={faqs.map(([question, answer]) => ({ question, answer }))} />
  </>;
}
