import Link from "next/link";
import { Arrow } from "@/components/icons";
import { ContactCta, PageIntro, SectionHeading } from "@/components/ui";
import { faqs, industries, process, services, siteConfig } from "@/content/site";
import { pageMetadata } from "@/lib/metadata";

export const metadata = pageMetadata("Digital Marketing Agency in Nepal", "GrowthLabs by Rohan Neure is a founder-led digital marketing agency in Nepal helping businesses grow with SEO, ads, websites, social media, content, CRO, and strategy.", "/digital-marketing-agency-in-nepal");

const comparisons = [
  ["Random posts and boosted content", "Strategy-led content and campaign planning"],
  ["SEO without clear page mapping", "Keyword clustering, intent mapping, and page structure"],
  ["Ads without conversion planning", "Paid ads connected to landing pages and CRO"],
  ["Websites focused only on design", "Websites focused on SEO, trust, speed, and leads"],
  ["Reports without useful next steps", "Insight-led reporting and improvement actions"],
  ["The same package for every business", "A business-specific digital marketing roadmap"],
];

export default function AgencyPage() {
  const schemas = [
    { "@context": "https://schema.org", "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: "Home", item: siteConfig.domain }, { "@type": "ListItem", position: 2, name: "Digital Marketing Agency in Nepal", item: `${siteConfig.domain}/digital-marketing-agency-in-nepal` }] },
    { "@context": "https://schema.org", "@type": "Service", name: "Digital Marketing Services in Nepal", serviceType: "Digital marketing", areaServed: [{ "@type": "Country", name: "Nepal" }, { "@type": "City", name: "Kathmandu" }, { "@type": "City", name: "Lalitpur" }, { "@type": "City", name: "Bhaktapur" }], provider: { "@type": "ProfessionalService", name: siteConfig.brandName, url: siteConfig.domain, founder: { "@type": "Person", name: siteConfig.fullName } } },
    { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: faqs.map((item) => ({ "@type": "Question", name: item.question, acceptedAnswer: { "@type": "Answer", text: item.answer } })) },
  ];
  return <>
    <PageIntro eyebrow="GrowthLabs / Nepal" title="Digital marketing agency in Nepal built for ranking, leads, and growth."><p>GrowthLabs by Rohan Neure connects SEO, paid ads, social media, website strategy, landing pages, content, local SEO, CRO, and tracking into one full-funnel system.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link className="button button-primary" href="/contact">Talk to Rohan <Arrow /></Link><Link className="button" href="/services">Explore services <Arrow /></Link></div></PageIntro>

    <section className="section"><div className="shell"><SectionHeading eyebrow="The challenge" title="Effort is not the missing piece. Connection is." copy="Many businesses post, boost, run ads, publish blogs, and redesign websites without consistent leads, rankings, enquiries, bookings, or sales. The channels exist, but the system does not." /><div className="mt-14 grid gap-8 md:ml-[25%] md:grid-cols-2"><article className="card"><h3 className="font-serif text-2xl">Websites without search or conversion</h3><p className="mt-3 leading-7 text-[var(--muted)]">Weak service pages, thin messaging, unclear calls to action, and no SEO structure make every other channel work harder.</p></article><article className="card"><h3 className="font-serif text-2xl">SEO without a keyword map</h3><p className="mt-3 leading-7 text-[var(--muted)]">Strong SEO needs research, clustering, competitor analysis, intent mapping, technical foundations, useful depth, and internal linking.</p></article><article className="card"><h3 className="font-serif text-2xl">Ads without a journey</h3><p className="mt-3 leading-7 text-[var(--muted)]">Budget cannot compensate for a weak offer, mismatched creative, an unclear landing page, broken tracking, or slow follow-up.</p></article><article className="card"><h3 className="font-serif text-2xl">Activity without strategy</h3><p className="mt-3 leading-7 text-[var(--muted)]">Social, search, content, paid media, and CRO should support one journey from visibility to trust to enquiry.</p></article></div></div></section>

    <section className="section bg-[linear-gradient(135deg,#21170d,#4a2005)] text-[var(--paper)]"><div className="shell"><SectionHeading eyebrow="Core services" title="Digital marketing services that work together." copy="Each capability can solve a focused challenge. The strongest results come when the right capabilities support one coherent growth plan." /><div className="mt-16 grid gap-10 md:grid-cols-2">{services.map((service, index) => <article className="border-t border-white/30 pt-5" key={service.slug}><p className="eyebrow !text-[var(--sun)]">0{index + 1}</p><h3 className="mt-5 font-serif text-3xl">{service.title}</h3><p className="mt-4 leading-7 text-white/65">{service.summary}</p><ul className="mt-6 grid gap-2 sm:grid-cols-2">{service.capabilities.map((item) => <li className="border-t border-white/15 py-2 text-sm text-white/75" key={item}>{item}</li>)}</ul></article>)}</div></div></section>

    <section className="section"><div className="shell"><SectionHeading eyebrow="Kathmandu & Nepal" title="Local context, full-funnel thinking." copy="GrowthLabs supports Kathmandu Valley and businesses across Nepal. Strategy reflects how customers search, compare providers, read reviews, visit social profiles, judge trust, and decide to make contact." /><div className="mt-12 grid gap-4 md:ml-[25%] md:grid-cols-2">{["Local keyword targeting", "Google Business Profile optimisation", "Kathmandu service landing pages", "Location-based ad campaigns", "Review and trust strategy", "Website and landing-page improvements", "Local SEO structure", "Lead-generation campaigns"].map((item) => <p className="border-t border-[var(--line)] py-3" key={item}>{item}</p>)}</div></div></section>

    <section className="section"><div className="shell"><SectionHeading eyebrow="Why GrowthLabs" title="Founder-led strategy, connected execution." /><div className="mt-14 grid gap-8 md:ml-[25%] md:grid-cols-2">{siteConfig.values.map((value) => <article className="card" key={value.title}><h3 className="font-serif text-2xl">{value.title}</h3><p className="mt-3 leading-7 text-[var(--muted)]">{value.detail}</p></article>)}</div><div className="mt-10 flex flex-col gap-3 md:ml-[25%] sm:flex-row"><Link className="text-link" href="/seo-expert-in-nepal">Work with an SEO expert in Nepal <Arrow /></Link><Link className="text-link sm:ml-6" href="/seo-company-in-nepal">Explore SEO company services <Arrow /></Link></div></div></section>

    <section className="section"><div className="shell"><SectionHeading eyebrow="Process" title="Know what is happening—and why." /><ol className="mt-14 md:ml-[25%]">{process.map((step, index) => <li className="grid gap-3 border-t border-[var(--line)] py-6 sm:grid-cols-[4rem_1fr_2fr]" key={step.title}><span className="eyebrow">0{index + 1}</span><h3 className="font-serif text-2xl">{step.title}</h3><p className="leading-7 text-[var(--muted)]">{step.copy}</p></li>)}</ol></div></section>

    <section className="section"><div className="shell"><SectionHeading eyebrow="A clearer comparison" title="Typical agency activity vs a growth system." /><div className="mt-14 overflow-x-auto md:ml-[25%]"><table className="w-full min-w-[38rem] border-collapse text-left"><thead><tr><th className="border-b border-[var(--ink)] p-4">Typical agency approach</th><th className="border-b border-[var(--ink)] p-4 text-[var(--accent)]">GrowthLabs approach</th></tr></thead><tbody>{comparisons.map(([typical, growth]) => <tr key={typical}><td className="border-b border-[var(--line)] p-4 text-[var(--muted)]">{typical}</td><td className="border-b border-[var(--line)] p-4 font-semibold">{growth}</td></tr>)}</tbody></table></div></div></section>

    <section className="section"><div className="shell"><SectionHeading eyebrow="Industries" title="Different markets. The same need for clarity." /><div className="mt-14 grid gap-8 sm:grid-cols-2 lg:grid-cols-3">{industries.map((item) => <article className="card" key={item.title}><h3 className="font-serif text-2xl">{item.title}</h3><p className="mt-3 text-sm leading-6 text-[var(--muted)]">{item.copy}</p></article>)}</div></div></section>

    <section className="section"><div className="shell"><SectionHeading eyebrow="Planning & pricing" title="A package should reflect the problem—not a post count." copy="The right digital marketing plan depends on business goals, competition, website condition, keyword opportunity, content requirements, campaign complexity, landing-page needs, tracking, and ongoing optimisation." /><div className="mt-12 md:ml-[25%]"><Link className="button button-primary" href="/contact">Request a custom growth plan <Arrow /></Link></div></div></section>

    <section className="section"><div className="shell"><SectionHeading eyebrow="FAQ" title="Digital marketing in Nepal, answered." /><div className="mt-14 md:ml-[25%]">{faqs.map((item) => <details className="group border-t border-[var(--line)] py-5" key={item.question}><summary className="flex cursor-pointer list-none items-center justify-between gap-6 font-serif text-xl"><span>{item.question}</span><span aria-hidden="true" className="text-[var(--accent)] group-open:rotate-45">+</span></summary><p className="prose-copy mt-4 pr-8">{item.answer}</p></details>)}</div></div></section>
    <ContactCta />
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schemas).replace(/</g, "\\u003c") }} />
  </>;
}
