import Link from "next/link";
import { Arrow } from "@/components/icons";
import { PageIntro, SectionHeading } from "@/components/ui";
import { siteConfig } from "@/content/site";
import { pageMetadata } from "@/lib/metadata";

export const metadata = pageMetadata("SEO Company in Nepal | GrowthLabs SEO Services", "GrowthLabs is a founder-led SEO company in Nepal connecting technical SEO, content, local search, internal links, tracking and CRO for measurable growth.", "/seo-company-in-nepal");

const failures = [
  ["The report is busy, but the website is unchanged", "SEO creates value when decisions become implementation. Rankings, audits and task lists must lead to better pages, stronger foundations and clearer customer journeys."],
  ["Every keyword is treated as a separate target", "Closely related searches often belong on one strong page. Unstructured targeting creates thin URLs, duplicated copy and internal competition."],
  ["Content is produced without commercial architecture", "Articles cannot rescue missing service, location, category or industry pages. Useful content strengthens the URLs responsible for generating business."],
  ["Links are pursued without relevance or risk control", "Authority matters, but indiscriminate link schemes can waste budget or expose the site to risk. Relevance and destination quality come first."],
  ["Traffic is reported without conversion context", "An SEO company should explain which landing pages attract meaningful intent, where visitors stop and what could create qualified action."],
];
const capabilities = [
  ["Strategy and keyword architecture", "Market research, competitor review, keyword clustering, search-intent classification and keyword-to-page mapping establish what the website should rank for and where each topic belongs."],
  ["Technical SEO", "Crawl and indexation review, canonicals, redirects, sitemaps, robots rules, performance, mobile usability, duplicate controls, URL structure and schema recommendations strengthen the technical base."],
  ["On-page SEO", "Titles, descriptions, headings, copy, media, internal links, entity coverage and calls to action are improved according to intent and commercial value."],
  ["Commercial and supporting content", "GrowthLabs plans the service, location, industry and supporting content needed to create topical depth without manufacturing unnecessary pages."],
  ["Local SEO", "Local scope can include keyword mapping, Google Business Profile, business-information consistency, reviews, relevant citations and location-page guidance."],
  ["Internal linking and architecture", "Important pages receive meaningful contextual links and clear relationships so people and search engines can interpret the hierarchy."],
  ["Measurement and reporting", "Search Console, analytics and conversion data explain query mix, landing-page performance, qualified action and the next priority."],
  ["SEO and CRO", "Commercial organic pages are reviewed for offer clarity, trust, evidence, friction, mobile experience and calls to action."],
];
const ownership = ["Initial business, website, competitor and demand review", "Technical audit with prioritised recommendations", "Keyword universe, clusters and URL ownership map", "Page-level metadata, heading and content recommendations", "Commercial page and content briefs", "Internal-link plan and implementation guidance", "Google Business Profile and local SEO recommendations", "Analytics, Search Console and conversion review", "Monthly priorities, implementation support and performance analysis", "CRO recommendations for priority organic pages"];
const steps = [
  ["Discovery and baseline", "Define the audience, offers, markets, current performance, business conversions and constraints."],
  ["Demand and website audit", "Review keywords, competitors, technical health, content, links, local presence and page performance."],
  ["Roadmap and ownership", "Map clusters to URLs, rank opportunities and assign responsibilities, dependencies and measurement."],
  ["Implementation", "Improve technical foundations, commercial pages, content, internal links, local signals and conversion paths."],
  ["Review and iteration", "Evaluate query and landing-page movement, conversions and lead quality; then refine the next cycle."],
];
const comparison = ["Evidence relevant to your business model, with dates and context", "A clear explanation of how research becomes page and technical decisions", "Honest expectations about timing, competition and uncertainty", "Defined deliverables, ownership, approvals and reporting", "A plan for technical SEO, content, links, local relevance and conversion", "Direct access to strategic decision-makers", "Measurement tied to qualified business actions", "A method that changes when evidence challenges assumptions"];
const businessModels = [
  ["Local and professional services", "Service and location relevance, Google Business Profile, trust, calls and qualified enquiry paths matter more than publishing a large general blog."],
  ["Hotels and hospitality", "Property, room, destination, local-search and booking journeys need to work together across the website and third-party discovery."],
  ["Travel and trekking businesses", "Destination hubs, packages, itineraries, seasonal demand and practical planning content require clear ownership and accurate expert review."],
  ["Ecommerce and growing brands", "Category, product, filter, comparison and supporting content need scalable technical controls and measurement connected to commercial value."],
];
const scopeModels = [
  ["Audit or foundation", "A one-off technical, content, local, keyword-architecture or conversion review produces a prioritised roadmap with clear implementation requirements."],
  ["Ongoing SEO programme", "Recurring work can coordinate technical improvements, commercial pages, useful content, internal links, local signals, measurement and CRO."],
  ["Content and production", "Research, briefs, writing, subject-matter review, photography and other production responsibilities are priced and approved separately where needed."],
  ["Development and implementation", "The proposal distinguishes what GrowthLabs changes directly from work assigned to your developer, designer, writer or internal marketing team."],
];
const faqs = [
  ["What does an SEO company in Nepal do?", "An SEO company researches demand, improves technical foundations, maps keywords to pages, strengthens content and on-page signals, builds internal relevance, supports local visibility, measures performance and improves conversion paths. The exact mix depends on the website and business model."],
  ["Does GrowthLabs offer one-time SEO audits?", "Yes. A defined audit can identify technical, structural, content, local and conversion priorities. GrowthLabs can also provide a keyword map, roadmap or implementation support."],
  ["Is content writing included in SEO services?", "Content strategy, briefs and optimisation can be included. Full writing, subject-matter input, photography and production responsibilities are confirmed in the proposal."],
  ["Do you provide link building?", "Relevant authority and mentions can be part of SEO planning, but GrowthLabs does not position bulk or manipulative links as a substitute for a strong website."],
  ["Do you provide local SEO services in Nepal?", "Yes. Local work can include Google Business Profile, local keyword mapping, reviews, business-information consistency, relevant citations, location pages and conversion measurement."],
  ["How often will I receive reports?", "Cadence is agreed with scope. A useful report explains what changed, what was implemented, how priority queries and pages performed, which conversions occurred and what should happen next."],
  ["Can you work with an existing website team?", "Yes. GrowthLabs can collaborate with developers, designers, writers and internal teams through prioritised requirements, briefs, quality review and measurement."],
  ["Does GrowthLabs guarantee rankings?", "No. GrowthLabs commits to transparent strategy, ethical execution, reliable measurement and continuous improvement. Search-engine positions cannot responsibly be guaranteed."],
];

export default function SeoCompanyPage() {
  const schemas = [{ "@context": "https://schema.org", "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: "Home", item: siteConfig.domain }, { "@type": "ListItem", position: 2, name: "SEO Company in Nepal", item: `${siteConfig.domain}/seo-company-in-nepal` }] }, { "@context": "https://schema.org", "@type": "Service", name: "SEO Services in Nepal", areaServed: { "@type": "Country", name: "Nepal" }, provider: { "@type": "Organization", name: siteConfig.brandName, url: siteConfig.domain } }];
  return <>
    <PageIntro eyebrow="GrowthLabs · Founder-led SEO company" title="SEO company in Nepal for sustainable visibility and qualified growth."><p>GrowthLabs builds SEO systems around the complete path from search demand to business action: keyword architecture, sound technical foundations, useful content, strong internal links, local relevance, reliable measurement and pages designed to convert.</p><p className="mt-4">You get direct strategic involvement from founder Rohan Neure and a scope built around your market, website and growth priorities—not a generic list of monthly tasks.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link className="button button-primary" href="/contact">Get an SEO growth plan <Arrow /></Link><Link className="button" href="/seo-expert-in-nepal">Work directly with Rohan <Arrow /></Link></div><p className="mt-4 text-sm">Start with the website, current performance and commercial priority. GrowthLabs recommends scope after diagnosis.</p></PageIntro>
    <div className="border-y border-[var(--line)]"><ul className="shell grid py-1 text-sm font-semibold sm:grid-cols-2 lg:grid-cols-4">{["Founder-led strategy", "Technical + content + local SEO", "Keyword-to-page architecture", "Conversion-focused reporting"].map((item) => <li className="py-4" key={item}>{item}</li>)}</ul></div>
    <section className="section"><div className="shell"><SectionHeading eyebrow="Fix the operating system" title="More activity cannot compensate for the wrong priorities." /><div className="mt-14 grid gap-8 md:grid-cols-2 lg:grid-cols-3">{failures.map(([title, copy]) => <article className="card" key={title}><h3 className="font-serif text-2xl">{title}</h3><p className="mt-3 leading-7 text-[var(--muted)]">{copy}</p></article>)}</div></div></section>
    <section className="section bg-[linear-gradient(135deg,#21170d,#4a2005)] text-[var(--paper)]"><div className="shell"><SectionHeading eyebrow="The complete programme" title="Research, foundations, content and conversion—connected." /><div className="mt-16 grid gap-10 md:grid-cols-2">{capabilities.map(([title, copy], index) => <article className="border-t border-white/30 pt-5" key={title}><p className="eyebrow !text-[var(--sun)]">0{index + 1}</p><h3 className="mt-5 font-serif text-3xl">{title}</h3><p className="mt-4 leading-7 text-white/65">{copy}</p></article>)}</div></div></section>
    <section className="section"><div className="shell"><SectionHeading eyebrow="Defined ownership" title="Know what GrowthLabs is responsible for." copy="The proposal also states what GrowthLabs implements, what your team or developer handles, which inputs are required and how approvals work." /><ul className="mt-12 grid md:ml-[25%] md:grid-cols-2">{ownership.map((item) => <li className="border-t border-[var(--line)] py-4 pr-5" key={item}>{item}</li>)}</ul></div></section>
    <section className="section"><div className="shell"><SectionHeading eyebrow="From diagnosis to compounding improvement" title="An SEO programme with visible reasoning." /><ol className="mt-14 md:ml-[25%]">{steps.map(([title, copy], index) => <li className="grid gap-3 border-t border-[var(--line)] py-6 sm:grid-cols-[4rem_1fr_2fr]" key={title}><span className="eyebrow">0{index + 1}</span><h3 className="font-serif text-2xl">{title}</h3><p className="leading-7 text-[var(--muted)]">{copy}</p></li>)}</ol></div></section>
    <section className="section"><div className="shell"><SectionHeading eyebrow="Fit before labels" title="SEO company, agency or consultant?" copy="Choose the operating model according to the work, access and implementation support the business actually needs—not the most impressive label." /><div className="mt-14 grid gap-8 md:ml-[25%] md:grid-cols-2"><article className="card"><h3 className="font-serif text-2xl">Consultant or specialist</h3><p className="mt-3 leading-7 text-[var(--muted)]">Often the right choice for an audit, keyword architecture, technical direction, a prioritised roadmap, coaching, senior review or a second opinion for an internal team.</p></article><article className="card"><h3 className="font-serif text-2xl">Company or agency</h3><p className="mt-3 leading-7 text-[var(--muted)]">Often a better fit when technical, content, local-search, measurement and conversion work need consistent coordination and implementation across several owners.</p></article><article className="card md:col-span-2"><h3 className="font-serif text-2xl">The GrowthLabs model</h3><p className="mt-3 leading-7 text-[var(--muted)]">GrowthLabs operates as a founder-led SEO company. Rohan stays directly involved in research, architecture and priorities while the engagement expands only around implementation the website genuinely needs.</p></article></div><div className="mt-10 md:ml-[25%]"><Link className="text-link" href="/seo-expert-in-nepal">Prefer direct specialist support? Meet the SEO expert in Nepal <Arrow /></Link></div></div></section>
    <section className="section"><div className="shell"><SectionHeading eyebrow="A better definition of ‘best’" title="The best SEO company is the one that can prove fit." copy="No agency should award itself the title of best SEO company in Nepal. Compare the evidence, reasoning, responsibility and ability to improve when assumptions are wrong." /><ul className="mt-12 grid md:ml-[25%] md:grid-cols-2">{comparison.map((item) => <li className="border-t border-[var(--line)] py-4 pr-5" key={item}>{item}</li>)}</ul><p className="mt-8 border-l-2 border-[var(--accent)] pl-5 md:ml-[25%]">Avoid guaranteed rankings, unexplained bulk links, copied content plans, hidden outsourcing and retainers with no clear implementation responsibility.</p></div></section>
    <section className="section"><div className="shell"><SectionHeading eyebrow="Relevant experience by business model" title="SEO services shaped around how customers search and decide." copy="GrowthLabs supports service businesses, hotels, travel and trekking agencies, ecommerce brands, restaurants, startups, consultants, local organisations, professional-service providers and agencies needing specialist support. The architecture, proof and conversion signal change by model." /><div className="mt-14 grid gap-8 md:ml-[25%] md:grid-cols-2">{businessModels.map(([title, copy]) => <article className="card" key={title}><h3 className="font-serif text-2xl">{title}</h3><p className="mt-3 leading-7 text-[var(--muted)]">{copy}</p></article>)}</div><div className="mt-10 flex flex-wrap gap-5 md:ml-[25%]"><Link className="text-link" href="/hotel-digital-marketing-agency">Hotel digital marketing <Arrow /></Link><Link className="text-link" href="/seo-for-travel-agency">Travel-agency SEO <Arrow /></Link><Link className="text-link" href="/web-design-company-in-nepal">SEO-led web design <Arrow /></Link></div></div></section>
    <section className="section"><div className="shell"><SectionHeading eyebrow="Scope drives investment" title="A useful SEO proposal explains what creates the cost." copy="Pricing is influenced by site size, technical condition, services and markets, competition, content requirements, local scope, development support, reporting depth and implementation ownership. The quote should separate one-off foundations, recurring optimisation, production and technical implementation." /><div className="mt-14 grid gap-8 md:ml-[25%] md:grid-cols-2">{scopeModels.map(([title, copy]) => <article className="card" key={title}><h3 className="font-serif text-2xl">{title}</h3><p className="mt-3 leading-7 text-[var(--muted)]">{copy}</p></article>)}</div><div className="mt-10 border-l-2 border-[var(--accent)] pl-5 md:ml-[25%]"><p className="font-semibold">Timing follows the starting point.</p><p className="mt-2 max-w-3xl leading-7 text-[var(--muted)]">Technical corrections and improvements to established pages may create earlier movement. Competitive commercial visibility usually compounds over months and depends on authority, implementation speed, content quality and market change. GrowthLabs sets expectations by workstream and does not promise a universal result date.</p></div><div className="mt-10 md:ml-[25%]"><Link className="button button-primary" href="/contact">Get an SEO growth plan <Arrow /></Link></div></div></section>
    <section className="section"><div className="shell"><SectionHeading eyebrow="Before you choose an SEO provider" title="Questions about SEO services in Nepal." /><div className="mt-14 md:ml-[25%]">{faqs.map(([question, answer]) => <details className="group border-t border-[var(--line)] py-5" key={question}><summary className="flex min-h-11 cursor-pointer list-none items-center justify-between gap-6 font-serif text-xl"><span>{question}</span><span aria-hidden="true" className="text-[var(--accent)] group-open:rotate-45">+</span></summary><p className="prose-copy mt-4 pr-8">{answer}</p></details>)}</div></div></section>
    <section className="section bg-[var(--accent)] text-white"><div className="shell grid gap-8 md:grid-cols-[1fr_3fr]"><p className="eyebrow !text-white/65">Build an SEO system that compounds</p><div><h2 className="section-title">Get a plan for the pages, fixes and opportunities that matter most.</h2><p className="mt-6 max-w-2xl text-lg leading-8 text-white/75">Tell GrowthLabs what the business sells, who it serves and where organic growth is stuck.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link className="button border-white text-white hover:bg-white hover:text-[var(--accent)]" href="/contact">Get an SEO growth plan <Arrow /></Link><a className="button border-white/50 text-white hover:bg-white hover:text-[var(--accent)]" href={siteConfig.whatsapp} target="_blank" rel="noopener noreferrer">Call or WhatsApp {siteConfig.phoneDisplay} <Arrow direction="up-right" /></a></div><p className="mt-5 text-sm text-white/70">Email {siteConfig.email} with your website and priority market.</p></div></div></section>
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schemas).replace(/</g, "\\u003c") }} />
  </>;
}
